-- ClassName: ModuleScript
-- Roblox Path: game.ReplicatedStorage.Framework.GeneratedUI.GuiSpec

-- Decompiled with Potassium's decompiler.

local l__GuiSpecParts__1 = script.Parent:WaitForChild("GuiSpecParts");
return {
    require(l__GuiSpecParts__1:WaitForChild("Gui_25")),
    require(l__GuiSpecParts__1:WaitForChild("MainScreenGui_26")),
    require(l__GuiSpecParts__1:WaitForChild("PopupGui_27")),
    require(l__GuiSpecParts__1:WaitForChild("Temp_28"))
};