-- ClassName: ModuleScript
-- Roblox Path: game.ReplicatedStorage.Framework.GeneratedUI.GuiSpecParts.Gui_Shop_Select_8

-- Decompiled with Potassium's decompiler.

return {
    Attributes = {},
    Children = {
        {
            Attributes = {},
            Children = {},
            ClassName = "UICorner",
            Name = "UICorner",
            Properties = {}
        },
        {
            Attributes = {},
            Children = {},
            ClassName = "UIListLayout",
            Name = "UIListLayout",
            Properties = {
                FillDirection = Enum.FillDirection.Horizontal,
                Padding = UDim.new(0, 2),
                SortOrder = Enum.SortOrder.LayoutOrder,
                VerticalAlignment = Enum.VerticalAlignment.Center
            }
        },
        {
            Attributes = {},
            Children = {
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UITextSizeConstraint",
                    Name = "UITextSizeConstraint",
                    Properties = {}
                },
                {
                    Attributes = {},
                    Children = {
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UICorner",
                            Name = "UICorner",
                            Properties = {}
                        },
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UITextSizeConstraint",
                            Name = "UITextSizeConstraint",
                            Properties = {}
                        }
                    },
                    ClassName = "TextLabel",
                    Name = "Menu",
                    Properties = {
                        AnchorPoint = Vector2.new(0.5, 0.5),
                        BackgroundColor3 = Color3.new(0.443137288, 0.443137288, 0.443137288),
                        BackgroundTransparency = 1,
                        BorderColor3 = Color3.new(0, 0, 0),
                        BorderSizePixel = 0,
                        Font = Enum.Font.Unknown,
                        LayoutOrder = 1,
                        Position = UDim2.new(0.500000119, 0, 0.797401071, 0),
                        Size = UDim2.new(1.00000024, 0, 0.399845123, 0),
                        Text = "Skins",
                        TextColor3 = Color3.new(1, 1, 1),
                        TextScaled = true,
                        TextStrokeTransparency = 0.5,
                        TextWrapped = true,
                        ZIndex = 2
                    }
                },
                {
                    Attributes = {},
                    Children = {
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UICorner",
                            Name = "UICorner",
                            Properties = {
                                CornerRadius = UDim.new(1, 0)
                            }
                        },
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UITextSizeConstraint",
                            Name = "UITextSizeConstraint",
                            Properties = {}
                        },
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UIAspectRatioConstraint",
                            Name = "UIAspectRatioConstraint",
                            Properties = {}
                        },
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {
                                        CornerRadius = UDim.new(1, 0)
                                    }
                                },
                                {
                                    Attributes = {},
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UICorner",
                                            Name = "UICorner",
                                            Properties = {
                                                CornerRadius = UDim.new(1, 0)
                                            }
                                        }
                                    },
                                    ClassName = "ImageLabel",
                                    Name = "ImageLabel",
                                    Properties = {
                                        BackgroundTransparency = 1,
                                        Image = "rbxassetid://139715191732729",
                                        ScaleType = Enum.ScaleType.Crop,
                                        Size = UDim2.new(1, 0, 1, 0),
                                        ZIndex = 3
                                    }
                                }
                            },
                            ClassName = "Frame",
                            Name = "Layer_Clip",
                            Properties = {
                                BackgroundTransparency = 1,
                                ClipsDescendants = true,
                                Size = UDim2.new(1, 0, 1, 0)
                            }
                        }
                    },
                    ClassName = "ImageLabel",
                    Name = "Avatar",
                    Properties = {
                        AnchorPoint = Vector2.new(0.5, 0.5),
                        BackgroundColor3 = Color3.new(0.274509817, 0.274509817, 0.274509817),
                        BorderColor3 = Color3.new(0, 0, 0),
                        BorderSizePixel = 0,
                        LayoutOrder = 1,
                        Position = UDim2.new(0.5, 0, 0.5, 0),
                        Size = UDim2.new(0.708149433, 0, 0.999999166, 0)
                    }
                }
            },
            ClassName = "TextButton",
            Name = "Skins",
            Properties = {
                Active = false,
                AnchorPoint = Vector2.new(0.5, 0.5),
                AutoButtonColor = false,
                BackgroundColor3 = Color3.new(0.203921571, 0.203921571, 0.203921571),
                BackgroundTransparency = 0.20000000298023224,
                BorderColor3 = Color3.new(0, 0, 0),
                BorderSizePixel = 0,
                LayoutOrder = 1,
                Position = UDim2.new(0.0824705288, 0, 0.5, 0),
                Selectable = false,
                Size = UDim2.new(0.164941341, 0, 1, 0),
                Text = ""
            }
        },
        {
            Attributes = {},
            Children = {
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UITextSizeConstraint",
                    Name = "UITextSizeConstraint",
                    Properties = {}
                },
                {
                    Attributes = {},
                    Children = {
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UICorner",
                            Name = "UICorner",
                            Properties = {}
                        },
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UITextSizeConstraint",
                            Name = "UITextSizeConstraint",
                            Properties = {}
                        }
                    },
                    ClassName = "TextLabel",
                    Name = "Menu",
                    Properties = {
                        AnchorPoint = Vector2.new(0.5, 0.5),
                        BackgroundColor3 = Color3.new(0.443137288, 0.443137288, 0.443137288),
                        BackgroundTransparency = 1,
                        BorderColor3 = Color3.new(0, 0, 0),
                        BorderSizePixel = 0,
                        Font = Enum.Font.Unknown,
                        LayoutOrder = 1,
                        Position = UDim2.new(0.500000119, 0, 0.797401071, 0),
                        Size = UDim2.new(1.00000024, 0, 0.399845123, 0),
                        Text = "Accessories",
                        TextColor3 = Color3.new(1, 1, 1),
                        TextScaled = true,
                        TextWrapped = true,
                        ZIndex = 2
                    }
                },
                {
                    Attributes = {},
                    Children = {
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UICorner",
                            Name = "UICorner",
                            Properties = {
                                CornerRadius = UDim.new(1, 0)
                            }
                        },
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UITextSizeConstraint",
                            Name = "UITextSizeConstraint",
                            Properties = {}
                        },
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UIAspectRatioConstraint",
                            Name = "UIAspectRatioConstraint",
                            Properties = {}
                        },
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "ImageLabel",
                                    Name = "ImageLabel",
                                    Properties = {
                                        BackgroundTransparency = 1,
                                        Image = "rbxassetid://118126324532621",
                                        ScaleType = Enum.ScaleType.Fit,
                                        Size = UDim2.new(1, 0, 1, 0),
                                        ZIndex = 2
                                    }
                                }
                            },
                            ClassName = "Frame",
                            Name = "Layer_Hats",
                            Properties = {
                                AnchorPoint = Vector2.new(0.5, 0.5),
                                BackgroundTransparency = 1,
                                Position = UDim2.new(0.5, 0, 0.5, 0),
                                Size = UDim2.new(1.5, 0, 1.5, 0)
                            }
                        },
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {
                                        CornerRadius = UDim.new(1, 0)
                                    }
                                }
                            },
                            ClassName = "Frame",
                            Name = "Layer_Clip",
                            Properties = {
                                BackgroundTransparency = 1,
                                ClipsDescendants = true,
                                Size = UDim2.new(1, 0, 1, 0)
                            }
                        }
                    },
                    ClassName = "ImageLabel",
                    Name = "Avatar",
                    Properties = {
                        AnchorPoint = Vector2.new(0.5, 0.5),
                        BackgroundColor3 = Color3.new(0.274509817, 0.274509817, 0.274509817),
                        BorderColor3 = Color3.new(0, 0, 0),
                        BorderSizePixel = 0,
                        LayoutOrder = 1,
                        Position = UDim2.new(0.5, 0, 0.5, 0),
                        Size = UDim2.new(0.708149433, 0, 0.999999166, 0)
                    }
                }
            },
            ClassName = "TextButton",
            Name = "Accessories",
            Properties = {
                Active = false,
                AnchorPoint = Vector2.new(0.5, 0.5),
                AutoButtonColor = false,
                BackgroundColor3 = Color3.new(0.203921571, 0.203921571, 0.203921571),
                BackgroundTransparency = 0.20000000298023224,
                BorderColor3 = Color3.new(0, 0, 0),
                BorderSizePixel = 0,
                LayoutOrder = 2,
                Position = UDim2.new(0.249482363, 0, 0.5, 0),
                Selectable = false,
                Size = UDim2.new(0.164941311, 0, 1, 0),
                Text = ""
            }
        },
        {
            Attributes = {},
            Children = {
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UITextSizeConstraint",
                    Name = "UITextSizeConstraint",
                    Properties = {}
                },
                {
                    Attributes = {},
                    Children = {
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UICorner",
                            Name = "UICorner",
                            Properties = {}
                        },
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UITextSizeConstraint",
                            Name = "UITextSizeConstraint",
                            Properties = {}
                        }
                    },
                    ClassName = "TextLabel",
                    Name = "Menu",
                    Properties = {
                        AnchorPoint = Vector2.new(0.5, 0.5),
                        BackgroundColor3 = Color3.new(0.443137288, 0.443137288, 0.443137288),
                        BackgroundTransparency = 1,
                        BorderColor3 = Color3.new(0, 0, 0),
                        BorderSizePixel = 0,
                        Font = Enum.Font.Unknown,
                        LayoutOrder = 1,
                        Position = UDim2.new(0.500000119, 0, 0.797401071, 0),
                        Size = UDim2.new(1.00000024, 0, 0.399845123, 0),
                        Text = "Bots",
                        TextColor3 = Color3.new(1, 1, 1),
                        TextScaled = true,
                        TextWrapped = true,
                        ZIndex = 2
                    }
                },
                {
                    Attributes = {},
                    Children = {
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UICorner",
                            Name = "UICorner",
                            Properties = {
                                CornerRadius = UDim.new(1, 0)
                            }
                        },
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UITextSizeConstraint",
                            Name = "UITextSizeConstraint",
                            Properties = {}
                        },
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UIAspectRatioConstraint",
                            Name = "UIAspectRatioConstraint",
                            Properties = {}
                        }
                    },
                    ClassName = "ImageLabel",
                    Name = "Avatar",
                    Properties = {
                        AnchorPoint = Vector2.new(0.5, 0.5),
                        BackgroundColor3 = Color3.new(0.274509817, 0.274509817, 0.274509817),
                        BorderColor3 = Color3.new(0, 0, 0),
                        BorderSizePixel = 0,
                        LayoutOrder = 1,
                        Position = UDim2.new(0.5, 0, 0.5, 0),
                        Size = UDim2.new(0.708149433, 0, 0.999999166, 0)
                    }
                }
            },
            ClassName = "TextButton",
            Name = "Bots",
            Properties = {
                Active = false,
                AnchorPoint = Vector2.new(0.5, 0.5),
                AutoButtonColor = false,
                BackgroundColor3 = Color3.new(0.203921586, 0.203921586, 0.203921586),
                BackgroundTransparency = 0.20000000298023224,
                BorderColor3 = Color3.new(0, 0, 0),
                BorderSizePixel = 0,
                LayoutOrder = 5,
                Position = UDim2.new(0.750517726, 0, 0.5, 0),
                Selectable = false,
                Size = UDim2.new(0.164941236, 0, 1, 0),
                Text = "",
                Visible = false
            }
        },
        {
            Attributes = {},
            Children = {
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UITextSizeConstraint",
                    Name = "UITextSizeConstraint",
                    Properties = {}
                },
                {
                    Attributes = {},
                    Children = {
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UICorner",
                            Name = "UICorner",
                            Properties = {}
                        },
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UITextSizeConstraint",
                            Name = "UITextSizeConstraint",
                            Properties = {}
                        }
                    },
                    ClassName = "TextLabel",
                    Name = "Menu",
                    Properties = {
                        AnchorPoint = Vector2.new(0.5, 0.5),
                        BackgroundColor3 = Color3.new(0.443137288, 0.443137288, 0.443137288),
                        BackgroundTransparency = 1,
                        BorderColor3 = Color3.new(0, 0, 0),
                        BorderSizePixel = 0,
                        Font = Enum.Font.Unknown,
                        LayoutOrder = 1,
                        Position = UDim2.new(0.500000119, 0, 0.797401071, 0),
                        Size = UDim2.new(1.00000024, 0, 0.399845123, 0),
                        Text = "Cases",
                        TextColor3 = Color3.new(1, 1, 1),
                        TextScaled = true,
                        TextStrokeTransparency = 0.5,
                        TextWrapped = true,
                        ZIndex = 2
                    }
                },
                {
                    Attributes = {},
                    Children = {
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UITextSizeConstraint",
                            Name = "UITextSizeConstraint",
                            Properties = {}
                        },
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UIAspectRatioConstraint",
                            Name = "UIAspectRatioConstraint",
                            Properties = {}
                        }
                    },
                    ClassName = "ImageLabel",
                    Name = "Avatar",
                    Properties = {
                        AnchorPoint = Vector2.new(0.5, 0.5),
                        BackgroundColor3 = Color3.new(0.274509817, 0.274509817, 0.274509817),
                        BorderColor3 = Color3.new(0, 0, 0),
                        BorderSizePixel = 0,
                        Image = "rbxassetid://133112511930324",
                        LayoutOrder = 1,
                        Position = UDim2.new(0.5, 0, 0.5, 0),
                        Size = UDim2.new(0.708149433, 0, 0.999999166, 0)
                    }
                }
            },
            ClassName = "TextButton",
            Name = "Cases",
            Properties = {
                Active = false,
                AnchorPoint = Vector2.new(0.5, 0.5),
                AutoButtonColor = false,
                BackgroundColor3 = Color3.new(0.203921586, 0.203921586, 0.203921586),
                BackgroundTransparency = 0.20000000298023224,
                BorderColor3 = Color3.new(0, 0, 0),
                BorderSizePixel = 0,
                LayoutOrder = 4,
                Position = UDim2.new(0.583505988, 0, 0.5, 0),
                Selectable = false,
                Size = UDim2.new(0.16494137, 0, 1, 0),
                Text = ""
            }
        },
        {
            Attributes = {},
            Children = {
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UITextSizeConstraint",
                    Name = "UITextSizeConstraint",
                    Properties = {}
                },
                {
                    Attributes = {},
                    Children = {
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UICorner",
                            Name = "UICorner",
                            Properties = {}
                        },
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UITextSizeConstraint",
                            Name = "UITextSizeConstraint",
                            Properties = {}
                        }
                    },
                    ClassName = "TextLabel",
                    Name = "Menu",
                    Properties = {
                        AnchorPoint = Vector2.new(0.5, 0.5),
                        BackgroundColor3 = Color3.new(0.443137288, 0.443137288, 0.443137288),
                        BackgroundTransparency = 1,
                        BorderColor3 = Color3.new(0, 0, 0),
                        BorderSizePixel = 0,
                        Font = Enum.Font.Unknown,
                        LayoutOrder = 1,
                        Position = UDim2.new(0.500000119, 0, 0.797401071, 0),
                        Size = UDim2.new(1.00000024, 0, 0.399845123, 0),
                        Text = "Abilities",
                        TextColor3 = Color3.new(1, 1, 1),
                        TextScaled = true,
                        TextStrokeTransparency = 0.5,
                        TextWrapped = true,
                        ZIndex = 2
                    }
                },
                {
                    Attributes = {},
                    Children = {
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UICorner",
                            Name = "UICorner",
                            Properties = {
                                CornerRadius = UDim.new(1, 0)
                            }
                        },
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UITextSizeConstraint",
                            Name = "UITextSizeConstraint",
                            Properties = {}
                        },
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UIAspectRatioConstraint",
                            Name = "UIAspectRatioConstraint",
                            Properties = {}
                        }
                    },
                    ClassName = "ImageLabel",
                    Name = "Avatar",
                    Properties = {
                        AnchorPoint = Vector2.new(0.5, 0.5),
                        BackgroundColor3 = Color3.new(0.274509817, 0.274509817, 0.274509817),
                        BackgroundTransparency = 1,
                        BorderColor3 = Color3.new(0, 0, 0),
                        BorderSizePixel = 0,
                        Image = "rbxassetid://107648441182956",
                        LayoutOrder = 1,
                        Position = UDim2.new(0.5, 0, 0.5, 0),
                        Size = UDim2.new(0.708149433, 0, 0.999999166, 0)
                    }
                }
            },
            ClassName = "TextButton",
            Name = "Abilities",
            Properties = {
                Active = false,
                AnchorPoint = Vector2.new(0.5, 0.5),
                AutoButtonColor = false,
                BackgroundColor3 = Color3.new(0.203921586, 0.203921586, 0.203921586),
                BackgroundTransparency = 0.20000000298023224,
                BorderColor3 = Color3.new(0, 0, 0),
                BorderSizePixel = 0,
                LayoutOrder = 3,
                Position = UDim2.new(0.41649422, 0, 0.5, 0),
                Selectable = false,
                Size = UDim2.new(0.164941311, 0, 1, 0),
                Text = ""
            }
        },
        {
            Attributes = {},
            Children = {
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UITextSizeConstraint",
                    Name = "UITextSizeConstraint",
                    Properties = {}
                },
                {
                    Attributes = {},
                    Children = {
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UICorner",
                            Name = "UICorner",
                            Properties = {}
                        },
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UITextSizeConstraint",
                            Name = "UITextSizeConstraint",
                            Properties = {}
                        }
                    },
                    ClassName = "TextLabel",
                    Name = "Menu",
                    Properties = {
                        AnchorPoint = Vector2.new(0.5, 0.5),
                        BackgroundColor3 = Color3.new(0.443137288, 0.443137288, 0.443137288),
                        BackgroundTransparency = 1,
                        BorderColor3 = Color3.new(0, 0, 0),
                        BorderSizePixel = 0,
                        LayoutOrder = 1,
                        Position = UDim2.new(0.500000119, 0, 0.797401071, 0),
                        Size = UDim2.new(1.00000024, 0, 0.399845123, 0),
                        Text = "Gold",
                        TextColor3 = Color3.new(1, 0.90196079, 0.431372553),
                        TextScaled = true,
                        TextWrapped = true,
                        ZIndex = 2,
                        FontFace = Font.new("rbxasset://fonts/families/Montserrat.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
                        TextSize = 20,
                        TextStrokeTransparency = 1,
                        TextXAlignment = Enum.TextXAlignment.Right,
                        TextYAlignment = Enum.TextYAlignment.Center
                    }
                },
                {
                    Attributes = {},
                    Children = {
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UICorner",
                            Name = "UICorner",
                            Properties = {
                                CornerRadius = UDim.new(1, 0)
                            }
                        },
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UITextSizeConstraint",
                            Name = "UITextSizeConstraint",
                            Properties = {}
                        },
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UIAspectRatioConstraint",
                            Name = "UIAspectRatioConstraint",
                            Properties = {
                                AspectRatio = 1,
                                AspectType = Enum.AspectType.FitWithinMaxSize,
                                DominantAxis = Enum.DominantAxis.Width
                            }
                        }
                    },
                    ClassName = "ImageLabel",
                    Name = "Avatar",
                    Properties = {
                        AnchorPoint = Vector2.new(0.5, 0.5),
                        BackgroundColor3 = Color3.new(0.274509817, 0.274509817, 0.274509817),
                        BackgroundTransparency = 1,
                        BorderColor3 = Color3.new(0, 0, 0),
                        BorderSizePixel = 0,
                        Image = "rbxassetid://11713337390",
                        ImageColor3 = Color3.new(0, 0, 0),
                        LayoutOrder = 1,
                        Position = UDim2.new(0.5, 0, 0.5, 0),
                        Size = UDim2.new(0.708149433, 0, 0.999999166, 0),
                        ImageTransparency = 0,
                        ScaleType = Enum.ScaleType.Stretch,
                        SizeConstraint = Enum.SizeConstraint.RelativeXY,
                        ZIndex = 1
                    }
                }
            },
            ClassName = "TextButton",
            Name = "Gold",
            Properties = {
                Active = false,
                AnchorPoint = Vector2.new(0.5, 0.5),
                AutoButtonColor = false,
                BackgroundColor3 = Color3.new(0.203921586, 0.203921586, 0.203921586),
                BackgroundTransparency = 0.20000000298023224,
                BorderColor3 = Color3.new(0, 0, 0),
                BorderSizePixel = 0,
                LayoutOrder = 5,
                Position = UDim2.new(0.917529285, 0, 0.5, 0),
                Selectable = false,
                Size = UDim2.new(0.164941236, 0, 1, 0),
                Text = ""
            }
        }
    },
    ClassName = "Frame",
    Name = "Select",
    Properties = {
        AnchorPoint = Vector2.new(1, 0.5),
        BackgroundColor3 = Color3.new(0, 0, 0),
        BackgroundTransparency = 0.5,
        BorderColor3 = Color3.new(0, 0, 0),
        BorderSizePixel = 0,
        ClipsDescendants = true,
        Position = UDim2.new(0.914758384, 0, 0.0925264731, 0),
        Size = UDim2.new(0.897476673, 0, 0.119598784, 0)
    }
};