-- ClassName: ModuleScript
-- Roblox Path: game.ReplicatedStorage.Framework.GeneratedUI.GuiSpecParts.Gui_25

-- Decompiled with Potassium's decompiler.

return {
    Attributes = {},
    Children = {
        require(script.Parent.Gui_Servers_1),
        require(script.Parent.Gui_Menu_2),
        require(script.Parent.Gui_Shop_21),
        require(script.Parent.Gui_Trade_22),
        require(script.Parent.Gui_ActiveTradeSession_23),
        require(script.Parent.Gui_Abilities_24)
    },
    ClassName = "ScreenGui",
    Name = "Gui",
    Properties = {
        DisplayOrder = 50,
        IgnoreGuiInset = true,
        ResetOnSpawn = false,
        ZIndexBehavior = Enum.ZIndexBehavior.Sibling
    }
};