-- ClassName: ModuleScript
-- Roblox Path: game.ReplicatedStorage.Framework.GeneratedUI.GuiSpecParts.Gui_Shop_Gold_18

-- Decompiled with Potassium's decompiler.

return {
    Attributes = {},
    Children = {
        {
            Attributes = {},
            Children = {},
            ClassName = "UICorner",
            Name = "UICorner",
            Properties = {}
        },
        {
            Attributes = {},
            Children = {
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UICorner",
                    Name = "UICorner",
                    Properties = {}
                },
                {
                    Attributes = {
                        DonationGenerated = true
                    },
                    Children = {},
                    ClassName = "UIPadding",
                    Name = "UIPadding",
                    Properties = {
                        PaddingBottom = UDim.new(0, 12),
                        PaddingLeft = UDim.new(0, 8),
                        PaddingRight = UDim.new(0, 8),
                        PaddingTop = UDim.new(0, 8)
                    }
                },
                {
                    Attributes = {
                        DonationGenerated = true
                    },
                    Children = {},
                    ClassName = "UIListLayout",
                    Name = "UIListLayout",
                    Properties = {
                        HorizontalAlignment = Enum.HorizontalAlignment.Center,
                        Padding = UDim.new(0, 8),
                        SortOrder = Enum.SortOrder.LayoutOrder
                    }
                },
                {
                    Attributes = {
                        DonationGenerated = true
                    },
                    Children = {
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UITextSizeConstraint",
                            Name = "UITextSizeConstraint",
                            Properties = {}
                        }
                    },
                    ClassName = "TextLabel",
                    Name = "PACKSTitle",
                    Properties = {
                        BackgroundTransparency = 1,
                        Font = Enum.Font.GothamBlack,
                        Size = UDim2.new(1, -10, 0, 28),
                        Text = "ПАКИ",
                        TextColor3 = Color3.new(0.960784316, 0.960784316, 0.960784316),
                        TextScaled = true,
                        TextWrapped = true,
                        TextXAlignment = Enum.TextXAlignment.Left,
                        Visible = false
                    }
                },
                {
                    Attributes = {
                        DonationGenerated = true
                    },
                    Children = {
                        {
                            Attributes = {
                                DonationGenerated = true
                            },
                            Children = {},
                            ClassName = "UIListLayout",
                            Name = "UIListLayout",
                            Properties = {
                                Padding = UDim.new(0, 8),
                                SortOrder = Enum.SortOrder.LayoutOrder
                            }
                        },
                        {
                            Attributes = {
                                DonationGenerated = true
                            },
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {
                                        CornerRadius = UDim.new(0, 5)
                                    }
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UIStroke",
                                    Name = "UIStroke",
                                    Properties = {
                                        Thickness = 3
                                    }
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UIGradient",
                                    Name = "UIGradient",
                                    Properties = {}
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextLabel",
                                    Name = "Header",
                                    Properties = {
                                        BackgroundColor3 = Color3.new(1, 0.823529422, 0.176470593),
                                        BorderSizePixel = 0,
                                        Font = Enum.Font.GothamBlack,
                                        Size = UDim2.new(1, 0, 0, 28),
                                        Text = "Premium Bundle",
                                        TextColor3 = Color3.new(0.137254909, 0.0980392173, 0),
                                        TextScaled = true,
                                        TextWrapped = true
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextLabel",
                                    Name = "Timer",
                                    Properties = {
                                        BackgroundTransparency = 1,
                                        Font = Enum.Font.GothamBlack,
                                        Position = UDim2.new(0, 8, 0, 34),
                                        Size = UDim2.new(0, 110, 0, 24),
                                        Text = "08d 13h 17m",
                                        TextColor3 = Color3.new(1, 0.215686277, 0.215686277),
                                        TextScaled = true,
                                        TextStrokeTransparency = 0,
                                        TextWrapped = true,
                                        ZIndex = 4
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UICorner",
                                            Name = "UICorner",
                                            Properties = {
                                                CornerRadius = UDim.new(0, 4)
                                            }
                                        },
                                        {
                                            Attributes = {
                                                DonationGenerated = true
                                            },
                                            Children = {
                                                {
                                                    Attributes = {},
                                                    Children = {},
                                                    ClassName = "UITextSizeConstraint",
                                                    Name = "UITextSizeConstraint",
                                                    Properties = {}
                                                },
                                                {
                                                    Attributes = {},
                                                    Children = {},
                                                    ClassName = "UIGradient",
                                                    Name = "UIGradient",
                                                    Properties = {}
                                                }
                                            },
                                            ClassName = "TextLabel",
                                            Name = "FallbackImage",
                                            Properties = {
                                                BackgroundColor3 = Color3.new(0.921568632, 0.921568632, 0.921568632),
                                                Font = Enum.Font.GothamBlack,
                                                Size = UDim2.new(1, 0, 1, 0),
                                                Text = "Premium Bundle",
                                                TextColor3 = Color3.new(0.0588235296, 0.0588235296, 0.0588235296),
                                                TextScaled = true,
                                                TextWrapped = true
                                            }
                                        }
                                    },
                                    ClassName = "Frame",
                                    Name = "ImageBand",
                                    Properties = {
                                        BackgroundColor3 = Color3.new(0.0392156877, 0.0392156877, 0.0588235296),
                                        BackgroundTransparency = 0.25,
                                        BorderSizePixel = 0,
                                        ClipsDescendants = true,
                                        Position = UDim2.new(0, 7, 0, 28),
                                        Size = UDim2.new(1.00000012, -16, 0.169014081, 58)
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextLabel",
                                    Name = "Subtitle",
                                    Properties = {
                                        BackgroundTransparency = 1,
                                        Font = Enum.Font.GothamBlack,
                                        Position = UDim2.new(0, 10, 1, -62),
                                        Size = UDim2.new(1, -20, 0, 28),
                                        Text = "250K Gold + 5 кейсов + 2 билета босса",
                                        TextColor3 = Color3.new(1, 1, 1),
                                        TextScaled = true,
                                        TextStrokeTransparency = 0.25,
                                        TextWrapped = true
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UICorner",
                                            Name = "UICorner",
                                            Properties = {
                                                CornerRadius = UDim.new(0, 4)
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UIStroke",
                                            Name = "UIStroke",
                                            Properties = {
                                                Color = Color3.new(0, 0.372549027, 0.137254909),
                                                Thickness = 2
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        },
                                        {
                                            Attributes = {},
                                            Children = {
                                                {
                                                    Attributes = {},
                                                    Children = {
                                                        {
                                                            Attributes = {},
                                                            Children = {},
                                                            ClassName = "UIStroke",
                                                            Name = "UIStroke",
                                                            Properties = {
                                                                Thickness = 1.5,
                                                                Transparency = 0.5
                                                            }
                                                        },
                                                        {
                                                            Attributes = {},
                                                            Children = {},
                                                            ClassName = "UITextSizeConstraint",
                                                            Name = "UITextSizeConstraint",
                                                            Properties = {}
                                                        }
                                                    },
                                                    ClassName = "TextLabel",
                                                    Name = "Amount",
                                                    Properties = {
                                                        AnchorPoint = Vector2.new(0, 0.5),
                                                        AutomaticSize = Enum.AutomaticSize.X,
                                                        BackgroundColor3 = Color3.new(1, 1, 1),
                                                        BackgroundTransparency = 1,
                                                        BorderColor3 = Color3.new(0, 0, 0),
                                                        BorderSizePixel = 0,
                                                        LayoutOrder = 3,
                                                        Position = UDim2.new(0.840649843, 0, 0.500000417, 0),
                                                        Size = UDim2.new(-0.0701028779, 0, 1.01747024, 0),
                                                        Text = "799",
                                                        TextColor3 = Color3.new(1, 0.90196079, 0.431372553),
                                                        TextScaled = true,
                                                        TextSize = 20,
                                                        TextWrapped = true,
                                                        TextXAlignment = Enum.TextXAlignment.Right,
                                                        FontFace = Font.new("rbxasset://fonts/families/Montserrat.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
                                                        TextStrokeTransparency = 1,
                                                        TextYAlignment = Enum.TextYAlignment.Center
                                                    }
                                                },
                                                {
                                                    Attributes = {},
                                                    Children = {
                                                        {
                                                            Attributes = {},
                                                            Children = {},
                                                            ClassName = "UIAspectRatioConstraint",
                                                            Name = "UIAspectRatioConstraint",
                                                            Properties = {}
                                                        },
                                                        {
                                                            Attributes = {},
                                                            Children = {},
                                                            ClassName = "UISizeConstraint",
                                                            Name = "UISizeConstraint",
                                                            Properties = {
                                                                MaxSize = Vector2.new(30, 30),
                                                                MinSize = Vector2.new(0, 0)
                                                            }
                                                        }
                                                    },
                                                    ClassName = "ImageLabel",
                                                    Name = "ImageLabel",
                                                    Properties = {
                                                        AnchorPoint = Vector2.new(0.5, 0.5),
                                                        BackgroundTransparency = 1,
                                                        Image = "rbxassetid://11713337390",
                                                        ImageColor3 = Color3.new(0, 0, 0),
                                                        LayoutOrder = 2,
                                                        Position = UDim2.new(0.889260292, 0, 0.910417259, 0),
                                                        Size = UDim2.new(0.221479446, 0, 1.27280772, 0),
                                                        ImageTransparency = 0,
                                                        ScaleType = Enum.ScaleType.Stretch,
                                                        SizeConstraint = Enum.SizeConstraint.RelativeXY,
                                                        ZIndex = 1
                                                    }
                                                },
                                                {
                                                    Attributes = {},
                                                    Children = {},
                                                    ClassName = "UIListLayout",
                                                    Name = "UIListLayout",
                                                    Properties = {
                                                        FillDirection = Enum.FillDirection.Horizontal,
                                                        HorizontalAlignment = Enum.HorizontalAlignment.Center,
                                                        Padding = UDim.new(0, 3),
                                                        SortOrder = Enum.SortOrder.LayoutOrder,
                                                        VerticalAlignment = Enum.VerticalAlignment.Center
                                                    }
                                                },
                                                {
                                                    Attributes = {},
                                                    Children = {},
                                                    ClassName = "UICorner",
                                                    Name = "UICorner",
                                                    Properties = {
                                                        CornerRadius = UDim.new(0, 4)
                                                    }
                                                }
                                            },
                                            ClassName = "Frame",
                                            Name = "GoldValue",
                                            Properties = {
                                                AnchorPoint = Vector2.new(1, 0.5),
                                                BackgroundColor3 = Color3.new(0, 0, 0),
                                                BackgroundTransparency = 0.550000011920929,
                                                BorderColor3 = Color3.new(0, 0, 0),
                                                BorderSizePixel = 0,
                                                Position = UDim2.new(1, 0, 0.5, 0),
                                                Size = UDim2.new(1, 0, 1, 0),
                                                Visible = false
                                            }
                                        }
                                    },
                                    ClassName = "TextButton",
                                    Name = "Buy",
                                    Properties = {
                                        AutoButtonColor = false,
                                        BackgroundColor3 = Color3.new(0, 0.823529422, 0.274509817),
                                        BorderSizePixel = 0,
                                        Position = UDim2.new(0, 0, 1, -32),
                                        Size = UDim2.new(1, 0, 0, 32),
                                        Text = "R$ 799",
                                        TextColor3 = Color3.new(1, 0.90196079, 0.431372553),
                                        TextScaled = true,
                                        TextWrapped = true,
                                        FontFace = Font.new("rbxasset://fonts/families/Montserrat.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
                                        TextSize = 18,
                                        TextStrokeTransparency = 1,
                                        TextYAlignment = Enum.TextYAlignment.Center
                                    }
                                }
                            },
                            ClassName = "Frame",
                            Name = "PremiumBundle",
                            Properties = {
                                BackgroundColor3 = Color3.new(0.0980392173, 0.105882354, 0.117647059),
                                BorderSizePixel = 0,
                                ClipsDescendants = true,
                                LayoutOrder = 1,
                                Size = UDim2.new(1, 0, 0, 142)
                            }
                        },
                        {
                            Attributes = {
                                DonationGenerated = true
                            },
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {
                                        CornerRadius = UDim.new(0, 5)
                                    }
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UIStroke",
                                    Name = "UIStroke",
                                    Properties = {
                                        Thickness = 3
                                    }
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UIGradient",
                                    Name = "UIGradient",
                                    Properties = {}
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextLabel",
                                    Name = "Header",
                                    Properties = {
                                        BackgroundColor3 = Color3.new(1, 0.823529422, 0.176470593),
                                        BorderSizePixel = 0,
                                        Font = Enum.Font.GothamBlack,
                                        Size = UDim2.new(1, 0, 0, 28),
                                        Text = "True Blue Bundle",
                                        TextColor3 = Color3.new(0.137254909, 0.0980392173, 0),
                                        TextScaled = true,
                                        TextWrapped = true
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextLabel",
                                    Name = "Timer",
                                    Properties = {
                                        BackgroundTransparency = 1,
                                        Font = Enum.Font.GothamBlack,
                                        Position = UDim2.new(0, 8, 0, 34),
                                        Size = UDim2.new(0, 110, 0, 24),
                                        Text = "03d 04h 20m",
                                        TextColor3 = Color3.new(1, 0.215686277, 0.215686277),
                                        TextScaled = true,
                                        TextStrokeTransparency = 0,
                                        TextWrapped = true,
                                        ZIndex = 4
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UICorner",
                                            Name = "UICorner",
                                            Properties = {
                                                CornerRadius = UDim.new(0, 4)
                                            }
                                        },
                                        {
                                            Attributes = {
                                                DonationGenerated = true
                                            },
                                            Children = {
                                                {
                                                    Attributes = {},
                                                    Children = {},
                                                    ClassName = "UITextSizeConstraint",
                                                    Name = "UITextSizeConstraint",
                                                    Properties = {}
                                                },
                                                {
                                                    Attributes = {},
                                                    Children = {},
                                                    ClassName = "UIGradient",
                                                    Name = "UIGradient",
                                                    Properties = {}
                                                }
                                            },
                                            ClassName = "TextLabel",
                                            Name = "FallbackImage",
                                            Properties = {
                                                BackgroundColor3 = Color3.new(0.921568632, 0.921568632, 0.921568632),
                                                Font = Enum.Font.GothamBlack,
                                                Size = UDim2.new(1, 0, 1, 0),
                                                Text = "True Blue Bundle",
                                                TextColor3 = Color3.new(0.0588235296, 0.0588235296, 0.0588235296),
                                                TextScaled = true,
                                                TextWrapped = true
                                            }
                                        }
                                    },
                                    ClassName = "Frame",
                                    Name = "ImageBand",
                                    Properties = {
                                        BackgroundColor3 = Color3.new(0.0392156877, 0.0392156877, 0.0588235296),
                                        BackgroundTransparency = 0.25,
                                        BorderSizePixel = 0,
                                        ClipsDescendants = true,
                                        Position = UDim2.new(0, 8, 0, 28),
                                        Size = UDim2.new(1, -16, 0.178169042, 58)
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextLabel",
                                    Name = "Subtitle",
                                    Properties = {
                                        BackgroundTransparency = 1,
                                        Font = Enum.Font.GothamBlack,
                                        Position = UDim2.new(0, 10, 1, -62),
                                        Size = UDim2.new(1, -20, 0, 28),
                                        Text = "Blue skin pack + 500K Gold + lucky tokens",
                                        TextColor3 = Color3.new(1, 1, 1),
                                        TextScaled = true,
                                        TextStrokeTransparency = 0.25,
                                        TextWrapped = true
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UICorner",
                                            Name = "UICorner",
                                            Properties = {
                                                CornerRadius = UDim.new(0, 4)
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UIStroke",
                                            Name = "UIStroke",
                                            Properties = {
                                                Color = Color3.new(0, 0.372549027, 0.137254909),
                                                Thickness = 2
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextButton",
                                    Name = "Buy",
                                    Properties = {
                                        AutoButtonColor = false,
                                        BackgroundColor3 = Color3.new(0, 0.823529422, 0.274509817),
                                        BorderSizePixel = 0,
                                        Position = UDim2.new(0, 0, 1, -32),
                                        Size = UDim2.new(1, 0, 0, 32),
                                        Text = "R$ 1,499",
                                        TextColor3 = Color3.new(1, 0.90196079, 0.431372553),
                                        TextScaled = true,
                                        TextWrapped = true,
                                        FontFace = Font.new("rbxasset://fonts/families/Montserrat.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
                                        TextSize = 18,
                                        TextStrokeTransparency = 1,
                                        TextYAlignment = Enum.TextYAlignment.Center
                                    }
                                }
                            },
                            ClassName = "Frame",
                            Name = "TrueBlueBundle",
                            Properties = {
                                BackgroundColor3 = Color3.new(0.0980392173, 0.105882354, 0.117647059),
                                BorderSizePixel = 0,
                                ClipsDescendants = true,
                                LayoutOrder = 2,
                                Size = UDim2.new(1, 0, 0, 142)
                            }
                        }
                    },
                    ClassName = "Frame",
                    Name = "PACKS",
                    Properties = {
                        BackgroundTransparency = 1,
                        Size = UDim2.new(1, -10, 0, 292),
                        Visible = false
                    }
                },
                {
                    Attributes = {
                        DonationGenerated = true
                    },
                    Children = {
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UITextSizeConstraint",
                            Name = "UITextSizeConstraint",
                            Properties = {}
                        }
                    },
                    ClassName = "TextLabel",
                    Name = "LIFETIMESUBSCRIPTIONSTitle",
                    Properties = {
                        BackgroundTransparency = 1,
                        Font = Enum.Font.GothamBlack,
                        LayoutOrder = 2,
                        Size = UDim2.new(1, -10, 0, 28),
                        Text = "LIFETIME SUBSCRIPTIONS",
                        TextColor3 = Color3.new(0.960784316, 0.960784316, 0.960784316),
                        TextScaled = true,
                        TextWrapped = true,
                        TextXAlignment = Enum.TextXAlignment.Left
                    }
                },
                {
                    Attributes = {
                        DonationGenerated = true
                    },
                    Children = {
                        {
                            Attributes = {
                                DonationGenerated = true
                            },
                            Children = {},
                            ClassName = "UIListLayout",
                            Name = "UIListLayout",
                            Properties = {
                                FillDirection = Enum.FillDirection.Horizontal,
                                Padding = UDim.new(0, 8),
                                SortOrder = Enum.SortOrder.LayoutOrder,
                                VerticalAlignment = Enum.VerticalAlignment.Center
                            }
                        },
                        {
                            Attributes = {
                                DonationGenerated = true
                            },
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {
                                        CornerRadius = UDim.new(0, 5)
                                    }
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UIStroke",
                                    Name = "UIStroke",
                                    Properties = {
                                        Color = Color3.new(0, 0.823529422, 0.470588237),
                                        Thickness = 2
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextLabel",
                                    Name = "Header",
                                    Properties = {
                                        BackgroundColor3 = Color3.new(0, 0.823529422, 0.470588237),
                                        BorderSizePixel = 0,
                                        Font = Enum.Font.GothamBlack,
                                        Size = UDim2.new(1, 0, 0.174418598, 0),
                                        Text = "GO",
                                        TextColor3 = Color3.new(0, 0, 0),
                                        TextScaled = true,
                                        TextWrapped = true
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextLabel",
                                    Name = "Subtitle",
                                    Properties = {
                                        BackgroundTransparency = 1,
                                        Font = Enum.Font.GothamBold,
                                        Position = UDim2.new(0.0166989788, 0, 0.186046511, 0),
                                        Size = UDim2.new(0.966602027, 0, 0.104651161, 0),
                                        Text = "Forever",
                                        TextColor3 = Color3.new(1, 1, 1),
                                        TextScaled = true,
                                        TextWrapped = true
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextLabel",
                                    Name = "Features",
                                    Properties = {
                                        BackgroundTransparency = 1,
                                        Font = Enum.Font.GothamMedium,
                                        Position = UDim2.new(0.0208737236, 0, 0.302325577, 0),
                                        Size = UDim2.new(0.958252549, 0, 0.5, 0),
                                        Text = "",
                                        TextColor3 = Color3.new(0.90196079, 0.921568632, 1),
                                        TextScaled = true,
                                        TextWrapped = true,
                                        TextYAlignment = Enum.TextYAlignment.Top
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UICorner",
                                            Name = "UICorner",
                                            Properties = {
                                                CornerRadius = UDim.new(0, 4)
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UIStroke",
                                            Name = "UIStroke",
                                            Properties = {
                                                Color = Color3.new(0, 0.372549027, 0.137254909),
                                                Thickness = 2
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextButton",
                                    Name = "BuyGui",
                                    Properties = {
                                        AutoButtonColor = false,
                                        BackgroundColor3 = Color3.new(0, 0.823529422, 0.274509817),
                                        BorderSizePixel = 0,
                                        Position = UDim2.new(0, 0, 0.813953459, 0),
                                        Size = UDim2.new(1, 0, 0.186046511, 0),
                                        Text = "R$ 39",
                                        TextColor3 = Color3.new(1, 0.90196079, 0.431372553),
                                        TextScaled = true,
                                        TextWrapped = true,
                                        FontFace = Font.new("rbxasset://fonts/families/Montserrat.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
                                        TextSize = 18,
                                        TextStrokeTransparency = 1,
                                        TextYAlignment = Enum.TextYAlignment.Center
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UICorner",
                                            Name = "UICorner",
                                            Properties = {
                                                CornerRadius = UDim.new(0, 4)
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UIStroke",
                                            Name = "UIStroke",
                                            Properties = {
                                                Color = Color3.new(0, 0.372549027, 0.137254909),
                                                Thickness = 2
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextButton",
                                    Name = "Buy",
                                    Properties = {
                                        AutoButtonColor = false,
                                        BackgroundColor3 = Color3.new(0, 0.823529422, 0.274509817),
                                        BackgroundTransparency = 1,
                                        BorderSizePixel = 0,
                                        Font = Enum.Font.GothamBlack,
                                        Size = UDim2.new(1, 0, 1, 0),
                                        Text = "",
                                        TextColor3 = Color3.new(0, 0.117647059, 0.0588235296),
                                        TextScaled = true,
                                        TextWrapped = true
                                    }
                                }
                            },
                            ClassName = "Frame",
                            Name = "GO",
                            Properties = {
                                BackgroundColor3 = Color3.new(0.125490203, 0.13333334, 0.149019614),
                                BorderSizePixel = 0,
                                LayoutOrder = 1,
                                Size = UDim2.new(0.324862689, 0, 1, 0)
                            }
                        },
                        {
                            Attributes = {
                                DonationGenerated = true
                            },
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {
                                        CornerRadius = UDim.new(0, 5)
                                    }
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UIStroke",
                                    Name = "UIStroke",
                                    Properties = {
                                        Color = Color3.new(0, 0.647058845, 1),
                                        Thickness = 2
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextLabel",
                                    Name = "Header",
                                    Properties = {
                                        BackgroundColor3 = Color3.new(0, 0.647058845, 1),
                                        BorderSizePixel = 0,
                                        Font = Enum.Font.GothamBlack,
                                        Size = UDim2.new(1, 0, 0.174418598, 0),
                                        Text = "Plus",
                                        TextColor3 = Color3.new(0, 0, 0),
                                        TextScaled = true,
                                        TextWrapped = true
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextLabel",
                                    Name = "Subtitle",
                                    Properties = {
                                        BackgroundTransparency = 1,
                                        Font = Enum.Font.GothamBold,
                                        Position = UDim2.new(0.0166989788, 0, 0.186046511, 0),
                                        Size = UDim2.new(0.966602027, 0, 0.104651161, 0),
                                        Text = "Forever",
                                        TextColor3 = Color3.new(1, 1, 1),
                                        TextScaled = true,
                                        TextWrapped = true
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextLabel",
                                    Name = "Features",
                                    Properties = {
                                        BackgroundTransparency = 1,
                                        Font = Enum.Font.GothamMedium,
                                        Position = UDim2.new(0.0208737236, 0, 0.302325577, 0),
                                        Size = UDim2.new(0.958252549, 0, 0.5, 0),
                                        Text = "Plus tag and nickname color",
                                        TextColor3 = Color3.new(0.90196079, 0.921568632, 1),
                                        TextScaled = true,
                                        TextWrapped = true,
                                        TextYAlignment = Enum.TextYAlignment.Top,
                                        Visible = false
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UICorner",
                                            Name = "UICorner",
                                            Properties = {
                                                CornerRadius = UDim.new(0, 4)
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UIStroke",
                                            Name = "UIStroke",
                                            Properties = {
                                                Color = Color3.new(0, 0.372549027, 0.137254909),
                                                Thickness = 2
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextButton",
                                    Name = "BuyGui",
                                    Properties = {
                                        AutoButtonColor = false,
                                        BackgroundColor3 = Color3.new(0, 0.823529422, 0.274509817),
                                        BorderSizePixel = 0,
                                        Position = UDim2.new(0, 0, 0.813953459, 0),
                                        Size = UDim2.new(1, 0, 0.186046511, 0),
                                        Text = "R$ 499",
                                        TextColor3 = Color3.new(1, 0.90196079, 0.431372553),
                                        TextScaled = true,
                                        TextWrapped = true,
                                        FontFace = Font.new("rbxasset://fonts/families/Montserrat.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
                                        TextSize = 18,
                                        TextStrokeTransparency = 1,
                                        TextYAlignment = Enum.TextYAlignment.Center
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UICorner",
                                            Name = "UICorner",
                                            Properties = {
                                                CornerRadius = UDim.new(0, 4)
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UIStroke",
                                            Name = "UIStroke",
                                            Properties = {
                                                Color = Color3.new(0, 0.372549027, 0.137254909),
                                                Thickness = 2
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextButton",
                                    Name = "Buy",
                                    Properties = {
                                        AutoButtonColor = false,
                                        BackgroundColor3 = Color3.new(0, 0.823529422, 0.274509817),
                                        BackgroundTransparency = 1,
                                        BorderSizePixel = 0,
                                        Font = Enum.Font.GothamBlack,
                                        Size = UDim2.new(1, 0, 1, 0),
                                        Text = "",
                                        TextColor3 = Color3.new(0, 0.117647059, 0.0588235296),
                                        TextScaled = true,
                                        TextWrapped = true
                                    }
                                }
                            },
                            ClassName = "Frame",
                            Name = "Plus",
                            Properties = {
                                BackgroundColor3 = Color3.new(0.125490203, 0.13333334, 0.149019614),
                                BorderSizePixel = 0,
                                LayoutOrder = 2,
                                Size = UDim2.new(0.324862689, 0, 1, 0)
                            }
                        },
                        {
                            Attributes = {
                                DonationGenerated = true
                            },
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {
                                        CornerRadius = UDim.new(0, 5)
                                    }
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UIStroke",
                                    Name = "UIStroke",
                                    Properties = {
                                        Color = Color3.new(0.745098054, 0.313725501, 1),
                                        Thickness = 2
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextLabel",
                                    Name = "Header",
                                    Properties = {
                                        BackgroundColor3 = Color3.new(0.745098054, 0.313725501, 1),
                                        BorderSizePixel = 0,
                                        Font = Enum.Font.GothamBlack,
                                        Size = UDim2.new(1, 0, 0.174418598, 0),
                                        Text = "Pro",
                                        TextColor3 = Color3.new(0, 0, 0),
                                        TextScaled = true,
                                        TextWrapped = true
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextLabel",
                                    Name = "Subtitle",
                                    Properties = {
                                        BackgroundTransparency = 1,
                                        Font = Enum.Font.GothamBold,
                                        Position = UDim2.new(0.0166989788, 0, 0.186046511, 0),
                                        Size = UDim2.new(0.966602027, 0, 0.104651161, 0),
                                        Text = "Forever",
                                        TextColor3 = Color3.new(1, 1, 1),
                                        TextScaled = true,
                                        TextWrapped = true
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextLabel",
                                    Name = "Features",
                                    Properties = {
                                        BackgroundTransparency = 1,
                                        Font = Enum.Font.GothamMedium,
                                        Position = UDim2.new(0.0208737236, 0, 0.302325577, 0),
                                        Size = UDim2.new(0.958252549, 0, 0.5, 0),
                                        Text = "Pro tag and nickname color",
                                        TextColor3 = Color3.new(0.90196079, 0.921568632, 1),
                                        TextScaled = true,
                                        TextWrapped = true,
                                        TextYAlignment = Enum.TextYAlignment.Top,
                                        Visible = false
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UICorner",
                                            Name = "UICorner",
                                            Properties = {
                                                CornerRadius = UDim.new(0, 4)
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UIStroke",
                                            Name = "UIStroke",
                                            Properties = {
                                                Color = Color3.new(0, 0.372549027, 0.137254909),
                                                Thickness = 2
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextButton",
                                    Name = "BuyGui",
                                    Properties = {
                                        AutoButtonColor = false,
                                        BackgroundColor3 = Color3.new(0, 0.823529422, 0.274509817),
                                        BorderSizePixel = 0,
                                        Position = UDim2.new(0, 0, 0.813953459, 0),
                                        Size = UDim2.new(1, 0, 0.186046511, 0),
                                        Text = "R$ 4,399",
                                        TextColor3 = Color3.new(1, 0.90196079, 0.431372553),
                                        TextScaled = true,
                                        TextWrapped = true,
                                        FontFace = Font.new("rbxasset://fonts/families/Montserrat.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
                                        TextSize = 18,
                                        TextStrokeTransparency = 1,
                                        TextYAlignment = Enum.TextYAlignment.Center
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UICorner",
                                            Name = "UICorner",
                                            Properties = {
                                                CornerRadius = UDim.new(0, 4)
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UIStroke",
                                            Name = "UIStroke",
                                            Properties = {
                                                Color = Color3.new(0, 0.372549027, 0.137254909),
                                                Thickness = 2
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextButton",
                                    Name = "Buy",
                                    Properties = {
                                        AutoButtonColor = false,
                                        BackgroundColor3 = Color3.new(0, 0.823529422, 0.274509817),
                                        BackgroundTransparency = 1,
                                        BorderSizePixel = 0,
                                        Font = Enum.Font.GothamBlack,
                                        Size = UDim2.new(1, 0, 1, 0),
                                        Text = "",
                                        TextColor3 = Color3.new(0, 0.117647059, 0.0588235296),
                                        TextScaled = true,
                                        TextWrapped = true
                                    }
                                }
                            },
                            ClassName = "Frame",
                            Name = "Pro",
                            Properties = {
                                BackgroundColor3 = Color3.new(0.125490203, 0.13333334, 0.149019614),
                                BorderSizePixel = 0,
                                LayoutOrder = 3,
                                Size = UDim2.new(0.324862689, 0, 1, 0)
                            }
                        }
                    },
                    ClassName = "Frame",
                    Name = "LIFETIMESUBSCRIPTIONS",
                    Properties = {
                        BackgroundTransparency = 1,
                        LayoutOrder = 3,
                        Size = UDim2.new(1, 0, 0.400000006, 0)
                    }
                },
                {
                    Attributes = {
                        DonationGenerated = true
                    },
                    Children = {
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UITextSizeConstraint",
                            Name = "UITextSizeConstraint",
                            Properties = {}
                        }
                    },
                    ClassName = "TextLabel",
                    Name = "GOLDTitle",
                    Properties = {
                        BackgroundTransparency = 1,
                        Size = UDim2.new(1, -10, 0, 28),
                        Text = "GOLD",
                        TextColor3 = Color3.new(1, 0.90196079, 0.431372553),
                        TextScaled = true,
                        TextWrapped = true,
                        TextXAlignment = Enum.TextXAlignment.Left,
                        FontFace = Font.new("rbxasset://fonts/families/Montserrat.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
                        TextSize = 20,
                        TextStrokeTransparency = 1,
                        TextYAlignment = Enum.TextYAlignment.Center
                    }
                },
                {
                    Attributes = {
                        DonationGenerated = true
                    },
                    Children = {
                        {
                            Attributes = {
                                DonationGenerated = true
                            },
                            Children = {},
                            ClassName = "UIListLayout",
                            Name = "UIListLayout",
                            Properties = {
                                FillDirection = Enum.FillDirection.Horizontal,
                                Padding = UDim.new(0, 8),
                                SortOrder = Enum.SortOrder.LayoutOrder,
                                VerticalAlignment = Enum.VerticalAlignment.Center
                            }
                        },
                        {
                            Attributes = {
                                DonationGenerated = true
                            },
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {
                                        CornerRadius = UDim.new(0, 5)
                                    }
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UIStroke",
                                    Name = "UIStroke",
                                    Properties = {
                                        Thickness = 2
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextLabel",
                                    Name = "Header",
                                    Properties = {
                                        BackgroundColor3 = Color3.new(1, 0.80392158, 0.274509817),
                                        BorderSizePixel = 0,
                                        Font = Enum.Font.GothamBlack,
                                        Size = UDim2.new(1, 0, 0.200000003, 0),
                                        Text = "+25,000",
                                        TextColor3 = Color3.new(0.0784313753, 0.0784313753, 0.0784313753),
                                        TextScaled = true,
                                        TextWrapped = true
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {},
                                    ClassName = "Frame",
                                    Name = "ImageHolder",
                                    Properties = {
                                        BackgroundTransparency = 1,
                                        ClipsDescendants = true,
                                        Position = UDim2.new(0, 4, 0, 33),
                                        Size = UDim2.new(1.00000012, -8, 1.09154928, -78)
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UICorner",
                                            Name = "UICorner",
                                            Properties = {
                                                CornerRadius = UDim.new(0, 4)
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UIStroke",
                                            Name = "UIStroke",
                                            Properties = {
                                                Color = Color3.new(0, 0.372549027, 0.137254909),
                                                Thickness = 2
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextButton",
                                    Name = "BuyGui",
                                    Properties = {
                                        AutoButtonColor = false,
                                        BackgroundColor3 = Color3.new(0, 0.823529422, 0.274509817),
                                        BorderSizePixel = 0,
                                        Position = UDim2.new(0, 0, 0.774999976, 0),
                                        Size = UDim2.new(1, 0, 0.224999994, 0),
                                        Text = "R$ 10",
                                        TextColor3 = Color3.new(1, 0.90196079, 0.431372553),
                                        TextScaled = true,
                                        TextWrapped = true,
                                        FontFace = Font.new("rbxasset://fonts/families/Montserrat.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
                                        TextSize = 18,
                                        TextStrokeTransparency = 1,
                                        TextYAlignment = Enum.TextYAlignment.Center
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UICorner",
                                            Name = "UICorner",
                                            Properties = {
                                                CornerRadius = UDim.new(0, 4)
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UIStroke",
                                            Name = "UIStroke",
                                            Properties = {
                                                Color = Color3.new(0, 0.372549027, 0.137254909),
                                                Thickness = 2
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextButton",
                                    Name = "Buy",
                                    Properties = {
                                        AutoButtonColor = false,
                                        BackgroundColor3 = Color3.new(0, 0.823529422, 0.274509817),
                                        BackgroundTransparency = 1,
                                        BorderSizePixel = 0,
                                        Font = Enum.Font.GothamBlack,
                                        Size = UDim2.new(1, 0, 1, 0),
                                        Text = "",
                                        TextColor3 = Color3.new(0, 0.117647059, 0.0588235296),
                                        TextScaled = true,
                                        TextWrapped = true
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {
                                                DonationGenerated = true
                                            },
                                            Children = {
                                                {
                                                    Attributes = {},
                                                    Children = {},
                                                    ClassName = "UITextSizeConstraint",
                                                    Name = "UITextSizeConstraint",
                                                    Properties = {}
                                                },
                                                {
                                                    Attributes = {},
                                                    Children = {},
                                                    ClassName = "UIGradient",
                                                    Name = "UIGradient",
                                                    Properties = {}
                                                }
                                            },
                                            ClassName = "TextLabel",
                                            Name = "FallbackImage",
                                            Properties = {
                                                AnchorPoint = Vector2.new(0.5, 0.5),
                                                BackgroundColor3 = Color3.new(0.921568632, 0.921568632, 0.921568632),
                                                Font = Enum.Font.GothamBlack,
                                                Position = UDim2.new(0.5, 0, 0.5, 0),
                                                Size = UDim2.new(1, 0, 1, 0),
                                                Text = "",
                                                TextColor3 = Color3.new(0.0588235296, 0.0588235296, 0.0588235296),
                                                TextScaled = true,
                                                TextWrapped = true
                                            }
                                        }
                                    },
                                    ClassName = "Frame",
                                    Name = "ImageHolder",
                                    Properties = {
                                        BackgroundTransparency = 1,
                                        ClipsDescendants = true,
                                        Position = UDim2.new(0.0283957627, 0, 0.203700766, 0),
                                        Size = UDim2.new(0.943208456, 0, 0.571299255, 0)
                                    }
                                }
                            },
                            ClassName = "Frame",
                            Name = "Gold1",
                            Properties = {
                                BackgroundColor3 = Color3.new(0.90196079, 0.90196079, 0.90196079),
                                BorderSizePixel = 0,
                                ClipsDescendants = true,
                                LayoutOrder = 1,
                                Position = UDim2.new(-4.13885104e-8, 0, 0, 0),
                                Size = UDim2.new(0.199182525, -6, 1, 0)
                            }
                        },
                        {
                            Attributes = {
                                DonationGenerated = true
                            },
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {
                                        CornerRadius = UDim.new(0, 5)
                                    }
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UIStroke",
                                    Name = "UIStroke",
                                    Properties = {
                                        Thickness = 2
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextLabel",
                                    Name = "Header",
                                    Properties = {
                                        BackgroundColor3 = Color3.new(1, 0.80392158, 0.274509817),
                                        BorderSizePixel = 0,
                                        Font = Enum.Font.GothamBlack,
                                        Size = UDim2.new(1, 0, 0.200000003, 0),
                                        Text = "+250,000",
                                        TextColor3 = Color3.new(0.0784313753, 0.0784313753, 0.0784313753),
                                        TextScaled = true,
                                        TextWrapped = true
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {},
                                    ClassName = "Frame",
                                    Name = "ImageHolder",
                                    Properties = {
                                        BackgroundTransparency = 1,
                                        ClipsDescendants = true,
                                        Position = UDim2.new(0, 4, 0, 33),
                                        Size = UDim2.new(1.00000012, -8, 1.09154928, -78)
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UICorner",
                                            Name = "UICorner",
                                            Properties = {
                                                CornerRadius = UDim.new(0, 4)
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UIStroke",
                                            Name = "UIStroke",
                                            Properties = {
                                                Color = Color3.new(0, 0.372549027, 0.137254909),
                                                Thickness = 2
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextButton",
                                    Name = "BuyGui",
                                    Properties = {
                                        AutoButtonColor = false,
                                        BackgroundColor3 = Color3.new(0, 0.823529422, 0.274509817),
                                        BorderSizePixel = 0,
                                        Position = UDim2.new(0, 0, 0.774647892, 0),
                                        Size = UDim2.new(1.00000012, 0, 0.225352094, 0),
                                        Text = "R$ 100",
                                        TextColor3 = Color3.new(1, 0.90196079, 0.431372553),
                                        TextScaled = true,
                                        TextWrapped = true,
                                        FontFace = Font.new("rbxasset://fonts/families/Montserrat.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
                                        TextSize = 18,
                                        TextStrokeTransparency = 1,
                                        TextYAlignment = Enum.TextYAlignment.Center
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UICorner",
                                            Name = "UICorner",
                                            Properties = {
                                                CornerRadius = UDim.new(0, 4)
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UIStroke",
                                            Name = "UIStroke",
                                            Properties = {
                                                Color = Color3.new(0, 0.372549027, 0.137254909),
                                                Thickness = 2
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextButton",
                                    Name = "Buy",
                                    Properties = {
                                        AutoButtonColor = false,
                                        BackgroundColor3 = Color3.new(0, 0.823529422, 0.274509817),
                                        BackgroundTransparency = 1,
                                        BorderSizePixel = 0,
                                        Font = Enum.Font.GothamBlack,
                                        Size = UDim2.new(1, 0, 1, 0),
                                        Text = "",
                                        TextColor3 = Color3.new(0, 0.117647059, 0.0588235296),
                                        TextScaled = true,
                                        TextWrapped = true
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {
                                                DonationGenerated = true
                                            },
                                            Children = {
                                                {
                                                    Attributes = {},
                                                    Children = {},
                                                    ClassName = "UITextSizeConstraint",
                                                    Name = "UITextSizeConstraint",
                                                    Properties = {}
                                                },
                                                {
                                                    Attributes = {},
                                                    Children = {},
                                                    ClassName = "UIGradient",
                                                    Name = "UIGradient",
                                                    Properties = {}
                                                }
                                            },
                                            ClassName = "TextLabel",
                                            Name = "FallbackImage",
                                            Properties = {
                                                AnchorPoint = Vector2.new(0.5, 0.5),
                                                BackgroundColor3 = Color3.new(0.921568632, 0.921568632, 0.921568632),
                                                Font = Enum.Font.GothamBlack,
                                                Position = UDim2.new(0.5, 0, 0.5, 0),
                                                Size = UDim2.new(1, 0, 1, 0),
                                                Text = "",
                                                TextColor3 = Color3.new(0.0588235296, 0.0588235296, 0.0588235296),
                                                TextScaled = true,
                                                TextWrapped = true
                                            }
                                        }
                                    },
                                    ClassName = "Frame",
                                    Name = "ImageHolder",
                                    Properties = {
                                        BackgroundTransparency = 1,
                                        ClipsDescendants = true,
                                        Position = UDim2.new(0.0283957627, 0, 0.203700766, 0),
                                        Size = UDim2.new(0.943208456, 0, 0.571299255, 0)
                                    }
                                }
                            },
                            ClassName = "Frame",
                            Name = "Gold2",
                            Properties = {
                                BackgroundColor3 = Color3.new(0.90196079, 0.90196079, 0.90196079),
                                BorderSizePixel = 0,
                                ClipsDescendants = true,
                                LayoutOrder = 2,
                                Position = UDim2.new(0.199615344, 0, 0, 0),
                                Size = UDim2.new(0.199000001, 0, 1, 0)
                            }
                        },
                        {
                            Attributes = {
                                DonationGenerated = true
                            },
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {
                                        CornerRadius = UDim.new(0, 5)
                                    }
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UIStroke",
                                    Name = "UIStroke",
                                    Properties = {
                                        Thickness = 2
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextLabel",
                                    Name = "Header",
                                    Properties = {
                                        BackgroundColor3 = Color3.new(1, 0.80392158, 0.274509817),
                                        BorderSizePixel = 0,
                                        Font = Enum.Font.GothamBlack,
                                        Size = UDim2.new(1, 0, 0.200000003, 0),
                                        Text = "+1,250,000",
                                        TextColor3 = Color3.new(0.0784313753, 0.0784313753, 0.0784313753),
                                        TextScaled = true,
                                        TextWrapped = true
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {
                                                DonationGenerated = true
                                            },
                                            Children = {
                                                {
                                                    Attributes = {},
                                                    Children = {},
                                                    ClassName = "UITextSizeConstraint",
                                                    Name = "UITextSizeConstraint",
                                                    Properties = {}
                                                },
                                                {
                                                    Attributes = {},
                                                    Children = {},
                                                    ClassName = "UIGradient",
                                                    Name = "UIGradient",
                                                    Properties = {}
                                                }
                                            },
                                            ClassName = "TextLabel",
                                            Name = "FallbackImage",
                                            Properties = {
                                                AnchorPoint = Vector2.new(0.5, 0.5),
                                                BackgroundColor3 = Color3.new(0.921568632, 0.921568632, 0.921568632),
                                                Font = Enum.Font.GothamBlack,
                                                Position = UDim2.new(0.5, 0, 0.5, 0),
                                                Size = UDim2.new(1, 0, 1, 0),
                                                Text = "",
                                                TextColor3 = Color3.new(0.0588235296, 0.0588235296, 0.0588235296),
                                                TextScaled = true,
                                                TextWrapped = true
                                            }
                                        }
                                    },
                                    ClassName = "Frame",
                                    Name = "ImageHolder",
                                    Properties = {
                                        BackgroundTransparency = 1,
                                        ClipsDescendants = true,
                                        Position = UDim2.new(0.0283957627, 0, 0.203700766, 0),
                                        Size = UDim2.new(0.943208456, 0, 0.571299255, 0)
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UICorner",
                                            Name = "UICorner",
                                            Properties = {
                                                CornerRadius = UDim.new(0, 4)
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UIStroke",
                                            Name = "UIStroke",
                                            Properties = {
                                                Color = Color3.new(0, 0.372549027, 0.137254909),
                                                Thickness = 2
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextButton",
                                    Name = "BuyGui",
                                    Properties = {
                                        AutoButtonColor = false,
                                        BackgroundColor3 = Color3.new(0, 0.823529422, 0.274509817),
                                        BorderSizePixel = 0,
                                        Position = UDim2.new(0, 0, 0.774999976, 0),
                                        Size = UDim2.new(1, 0, 0.224999994, 0),
                                        Text = "R$ 499",
                                        TextColor3 = Color3.new(1, 0.90196079, 0.431372553),
                                        TextScaled = true,
                                        TextWrapped = true,
                                        FontFace = Font.new("rbxasset://fonts/families/Montserrat.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
                                        TextSize = 18,
                                        TextStrokeTransparency = 1,
                                        TextYAlignment = Enum.TextYAlignment.Center
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextLabel",
                                    Name = "Bonus",
                                    Properties = {
                                        BackgroundTransparency = 1,
                                        Font = Enum.Font.GothamBlack,
                                        Position = UDim2.new(0.0283957627, 0, 0.660806477, 0),
                                        Size = UDim2.new(0.943208456, 0, 0.113064542, 0),
                                        Text = "Popular",
                                        TextColor3 = Color3.new(1, 0, 0),
                                        TextScaled = true,
                                        TextStrokeTransparency = 0.25,
                                        TextWrapped = true
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UICorner",
                                            Name = "UICorner",
                                            Properties = {
                                                CornerRadius = UDim.new(0, 4)
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UIStroke",
                                            Name = "UIStroke",
                                            Properties = {
                                                Color = Color3.new(0, 0.372549027, 0.137254909),
                                                Thickness = 2
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextButton",
                                    Name = "Buy",
                                    Properties = {
                                        AutoButtonColor = false,
                                        BackgroundColor3 = Color3.new(0, 0.823529422, 0.274509817),
                                        BackgroundTransparency = 1,
                                        BorderSizePixel = 0,
                                        Font = Enum.Font.GothamBlack,
                                        Size = UDim2.new(1, 0, 1, 0),
                                        Text = "",
                                        TextColor3 = Color3.new(0, 0.117647059, 0.0588235296),
                                        TextScaled = true,
                                        TextWrapped = true
                                    }
                                }
                            },
                            ClassName = "Frame",
                            Name = "Gold3",
                            Properties = {
                                BackgroundColor3 = Color3.new(0.90196079, 0.90196079, 0.90196079),
                                BorderSizePixel = 0,
                                ClipsDescendants = true,
                                LayoutOrder = 3,
                                Position = UDim2.new(0.399230659, 0, 0, 0),
                                Size = UDim2.new(0.19918254, -6, 1, 0)
                            }
                        },
                        {
                            Attributes = {
                                DonationGenerated = true
                            },
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {
                                        CornerRadius = UDim.new(0, 5)
                                    }
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UIStroke",
                                    Name = "UIStroke",
                                    Properties = {
                                        Thickness = 2
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextLabel",
                                    Name = "Header",
                                    Properties = {
                                        BackgroundColor3 = Color3.new(1, 0.80392158, 0.274509817),
                                        BorderSizePixel = 0,
                                        Font = Enum.Font.GothamBlack,
                                        Size = UDim2.new(1, 0, 0.200000003, 0),
                                        Text = "+2,500,000",
                                        TextColor3 = Color3.new(0.0784313753, 0.0784313753, 0.0784313753),
                                        TextScaled = true,
                                        TextWrapped = true
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {},
                                    ClassName = "Frame",
                                    Name = "ImageHolder",
                                    Properties = {
                                        BackgroundTransparency = 1,
                                        ClipsDescendants = true,
                                        Position = UDim2.new(0, 4, 0, 33),
                                        Size = UDim2.new(1.00000012, -8, 1.09154928, -78)
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UICorner",
                                            Name = "UICorner",
                                            Properties = {
                                                CornerRadius = UDim.new(0, 4)
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UIStroke",
                                            Name = "UIStroke",
                                            Properties = {
                                                Color = Color3.new(0, 0.372549027, 0.137254909),
                                                Thickness = 2
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextButton",
                                    Name = "BuyGui",
                                    Properties = {
                                        AutoButtonColor = false,
                                        BackgroundColor3 = Color3.new(0, 0.823529422, 0.274509817),
                                        BorderSizePixel = 0,
                                        Position = UDim2.new(0, 0, 0.774999976, 0),
                                        Size = UDim2.new(1, 0, 0.224999994, 0),
                                        Text = "R$ 999",
                                        TextColor3 = Color3.new(1, 0.90196079, 0.431372553),
                                        TextScaled = true,
                                        TextWrapped = true,
                                        FontFace = Font.new("rbxasset://fonts/families/Montserrat.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
                                        TextSize = 18,
                                        TextStrokeTransparency = 1,
                                        TextYAlignment = Enum.TextYAlignment.Center
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UICorner",
                                            Name = "UICorner",
                                            Properties = {
                                                CornerRadius = UDim.new(0, 4)
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UIStroke",
                                            Name = "UIStroke",
                                            Properties = {
                                                Color = Color3.new(0, 0.372549027, 0.137254909),
                                                Thickness = 2
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextButton",
                                    Name = "Buy",
                                    Properties = {
                                        AutoButtonColor = false,
                                        BackgroundColor3 = Color3.new(0, 0.823529422, 0.274509817),
                                        BackgroundTransparency = 1,
                                        BorderSizePixel = 0,
                                        Font = Enum.Font.GothamBlack,
                                        Size = UDim2.new(1, 0, 1, 0),
                                        Text = "",
                                        TextColor3 = Color3.new(0, 0.117647059, 0.0588235296),
                                        TextScaled = true,
                                        TextWrapped = true
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {
                                                DonationGenerated = true
                                            },
                                            Children = {
                                                {
                                                    Attributes = {},
                                                    Children = {},
                                                    ClassName = "UITextSizeConstraint",
                                                    Name = "UITextSizeConstraint",
                                                    Properties = {}
                                                },
                                                {
                                                    Attributes = {},
                                                    Children = {},
                                                    ClassName = "UIGradient",
                                                    Name = "UIGradient",
                                                    Properties = {}
                                                }
                                            },
                                            ClassName = "TextLabel",
                                            Name = "FallbackImage",
                                            Properties = {
                                                AnchorPoint = Vector2.new(0.5, 0.5),
                                                BackgroundColor3 = Color3.new(0.921568632, 0.921568632, 0.921568632),
                                                Font = Enum.Font.GothamBlack,
                                                Position = UDim2.new(0.5, 0, 0.5, 0),
                                                Size = UDim2.new(1, 0, 1, 0),
                                                Text = "",
                                                TextColor3 = Color3.new(0.0588235296, 0.0588235296, 0.0588235296),
                                                TextScaled = true,
                                                TextWrapped = true
                                            }
                                        }
                                    },
                                    ClassName = "Frame",
                                    Name = "ImageHolder",
                                    Properties = {
                                        BackgroundTransparency = 1,
                                        ClipsDescendants = true,
                                        Position = UDim2.new(0.0283957627, 0, 0.203700766, 0),
                                        Size = UDim2.new(0.943208456, 0, 0.571299255, 0)
                                    }
                                }
                            },
                            ClassName = "Frame",
                            Name = "Gold4",
                            Properties = {
                                BackgroundColor3 = Color3.new(0.90196079, 0.90196079, 0.90196079),
                                BorderSizePixel = 0,
                                ClipsDescendants = true,
                                LayoutOrder = 4,
                                Position = UDim2.new(0.605684876, 0, -0.402317524, 0),
                                Size = UDim2.new(0.199000001, -6, 1, 0)
                            }
                        },
                        {
                            Attributes = {
                                DonationGenerated = true
                            },
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {
                                        CornerRadius = UDim.new(0, 5)
                                    }
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UIStroke",
                                    Name = "UIStroke",
                                    Properties = {
                                        Thickness = 2
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextLabel",
                                    Name = "Header",
                                    Properties = {
                                        BackgroundColor3 = Color3.new(1, 0.80392158, 0.274509817),
                                        BorderSizePixel = 0,
                                        Font = Enum.Font.GothamBlack,
                                        Size = UDim2.new(1, 0, 0.200000003, 0),
                                        Text = "+40,000,000",
                                        TextColor3 = Color3.new(0.0784313753, 0.0784313753, 0.0784313753),
                                        TextScaled = true,
                                        TextWrapped = true
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {},
                                    ClassName = "Frame",
                                    Name = "ImageHolder",
                                    Properties = {
                                        BackgroundTransparency = 1,
                                        ClipsDescendants = true,
                                        Position = UDim2.new(0, 4, 0, 33),
                                        Size = UDim2.new(1.00000012, -8, 1.09154928, -78)
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UICorner",
                                            Name = "UICorner",
                                            Properties = {
                                                CornerRadius = UDim.new(0, 4)
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UIStroke",
                                            Name = "UIStroke",
                                            Properties = {
                                                Color = Color3.new(0, 0.372549027, 0.137254909),
                                                Thickness = 2
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextButton",
                                    Name = "BuyGui",
                                    Properties = {
                                        AutoButtonColor = false,
                                        BackgroundColor3 = Color3.new(0, 0.823529422, 0.274509817),
                                        BorderSizePixel = 0,
                                        Position = UDim2.new(0, 0, 0.774999976, 0),
                                        Size = UDim2.new(1, 0, 0.224999994, 0),
                                        Text = "R$ 16,000",
                                        TextColor3 = Color3.new(1, 0.90196079, 0.431372553),
                                        TextScaled = true,
                                        TextWrapped = true,
                                        FontFace = Font.new("rbxasset://fonts/families/Montserrat.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
                                        TextSize = 18,
                                        TextStrokeTransparency = 1,
                                        TextYAlignment = Enum.TextYAlignment.Center
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UICorner",
                                            Name = "UICorner",
                                            Properties = {
                                                CornerRadius = UDim.new(0, 4)
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UIStroke",
                                            Name = "UIStroke",
                                            Properties = {
                                                Color = Color3.new(0, 0.372549027, 0.137254909),
                                                Thickness = 2
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextButton",
                                    Name = "Buy",
                                    Properties = {
                                        AutoButtonColor = false,
                                        BackgroundColor3 = Color3.new(0, 0.823529422, 0.274509817),
                                        BackgroundTransparency = 1,
                                        BorderSizePixel = 0,
                                        Font = Enum.Font.GothamBlack,
                                        Size = UDim2.new(1, 0, 1, 0),
                                        Text = "",
                                        TextColor3 = Color3.new(0, 0.117647059, 0.0588235296),
                                        TextScaled = true,
                                        TextWrapped = true
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {
                                                DonationGenerated = true
                                            },
                                            Children = {
                                                {
                                                    Attributes = {},
                                                    Children = {},
                                                    ClassName = "UITextSizeConstraint",
                                                    Name = "UITextSizeConstraint",
                                                    Properties = {}
                                                },
                                                {
                                                    Attributes = {},
                                                    Children = {},
                                                    ClassName = "UIGradient",
                                                    Name = "UIGradient",
                                                    Properties = {}
                                                }
                                            },
                                            ClassName = "TextLabel",
                                            Name = "FallbackImage",
                                            Properties = {
                                                AnchorPoint = Vector2.new(0.5, 0.5),
                                                BackgroundColor3 = Color3.new(0.921568632, 0.921568632, 0.921568632),
                                                Font = Enum.Font.GothamBlack,
                                                Position = UDim2.new(0.5, 0, 0.5, 0),
                                                Size = UDim2.new(1, 0, 1, 0),
                                                Text = "",
                                                TextColor3 = Color3.new(0.0588235296, 0.0588235296, 0.0588235296),
                                                TextScaled = true,
                                                TextWrapped = true
                                            }
                                        }
                                    },
                                    ClassName = "Frame",
                                    Name = "ImageHolder",
                                    Properties = {
                                        BackgroundTransparency = 1,
                                        ClipsDescendants = true,
                                        Position = UDim2.new(0.0283957627, 0, 0.203700766, 0),
                                        Size = UDim2.new(0.943208456, 0, 0.571299255, 0)
                                    }
                                }
                            },
                            ClassName = "Frame",
                            Name = "Gold5",
                            Properties = {
                                BackgroundColor3 = Color3.new(0.90196079, 0.90196079, 0.90196079),
                                BorderSizePixel = 0,
                                ClipsDescendants = true,
                                LayoutOrder = 5,
                                Position = UDim2.new(0.798461378, 0, 0, 0),
                                Size = UDim2.new(0.19918254, -6, 1, 0)
                            }
                        }
                    },
                    ClassName = "Frame",
                    Name = "Gold",
                    Properties = {
                        BackgroundTransparency = 1,
                        Size = UDim2.new(1, -10, 0.400000006, 0)
                    }
                },
                {
                    Attributes = {
                        DonationGenerated = true
                    },
                    Children = {
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UITextSizeConstraint",
                            Name = "UITextSizeConstraint",
                            Properties = {}
                        }
                    },
                    ClassName = "TextLabel",
                    Name = "GOODSTitle",
                    Properties = {
                        BackgroundTransparency = 1,
                        Font = Enum.Font.GothamBlack,
                        Size = UDim2.new(1, -10, 0, 28),
                        Text = "ТОВАРЫ",
                        TextColor3 = Color3.new(0.960784316, 0.960784316, 0.960784316),
                        TextScaled = true,
                        TextWrapped = true,
                        TextXAlignment = Enum.TextXAlignment.Left,
                        Visible = false
                    }
                },
                {
                    Attributes = {
                        DonationGenerated = true
                    },
                    Children = {
                        {
                            Attributes = {
                                DonationGenerated = true
                            },
                            Children = {},
                            ClassName = "UIListLayout",
                            Name = "UIListLayout",
                            Properties = {
                                FillDirection = Enum.FillDirection.Horizontal,
                                Padding = UDim.new(0, 8),
                                SortOrder = Enum.SortOrder.LayoutOrder,
                                VerticalAlignment = Enum.VerticalAlignment.Center
                            }
                        },
                        {
                            Attributes = {
                                DonationGenerated = true
                            },
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {
                                        CornerRadius = UDim.new(0, 5)
                                    }
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UIStroke",
                                    Name = "UIStroke",
                                    Properties = {
                                        Thickness = 2
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextLabel",
                                    Name = "Header",
                                    Properties = {
                                        BackgroundColor3 = Color3.new(1, 0.80392158, 0.274509817),
                                        BorderSizePixel = 0,
                                        Font = Enum.Font.GothamBlack,
                                        Size = UDim2.new(1, 0, 0, 29),
                                        Text = "ВОЗРОЖДЕНИЕ БОССА",
                                        TextColor3 = Color3.new(0.0784313753, 0.0784313753, 0.0784313753),
                                        TextScaled = true,
                                        TextWrapped = true
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {
                                                DonationGenerated = true
                                            },
                                            Children = {
                                                {
                                                    Attributes = {},
                                                    Children = {},
                                                    ClassName = "UITextSizeConstraint",
                                                    Name = "UITextSizeConstraint",
                                                    Properties = {}
                                                },
                                                {
                                                    Attributes = {},
                                                    Children = {},
                                                    ClassName = "UIGradient",
                                                    Name = "UIGradient",
                                                    Properties = {}
                                                }
                                            },
                                            ClassName = "TextLabel",
                                            Name = "FallbackImage",
                                            Properties = {
                                                BackgroundColor3 = Color3.new(0.921568632, 0.921568632, 0.921568632),
                                                Font = Enum.Font.GothamBlack,
                                                Size = UDim2.new(1, 0, 1, 0),
                                                Text = "1 билет",
                                                TextColor3 = Color3.new(0.0588235296, 0.0588235296, 0.0588235296),
                                                TextScaled = true,
                                                TextWrapped = true
                                            }
                                        }
                                    },
                                    ClassName = "Frame",
                                    Name = "ImageHolder",
                                    Properties = {
                                        BackgroundTransparency = 1,
                                        ClipsDescendants = true,
                                        Position = UDim2.new(0, 4, 0, 33),
                                        Size = UDim2.new(1.00000012, -8, 1.07558143, -78)
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UICorner",
                                            Name = "UICorner",
                                            Properties = {
                                                CornerRadius = UDim.new(0, 4)
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UIStroke",
                                            Name = "UIStroke",
                                            Properties = {
                                                Color = Color3.new(0, 0.372549027, 0.137254909),
                                                Thickness = 2
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextButton",
                                    Name = "Buy",
                                    Properties = {
                                        BackgroundColor3 = Color3.new(0, 0.823529422, 0.274509817),
                                        BorderSizePixel = 0,
                                        Position = UDim2.new(0, 0, 1, -32),
                                        Size = UDim2.new(1, 0, 0, 32),
                                        Text = "R$ 50",
                                        TextColor3 = Color3.new(1, 0.90196079, 0.431372553),
                                        TextScaled = true,
                                        TextWrapped = true,
                                        FontFace = Font.new("rbxasset://fonts/families/Montserrat.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
                                        TextSize = 18,
                                        TextStrokeTransparency = 1,
                                        TextYAlignment = Enum.TextYAlignment.Center
                                    }
                                }
                            },
                            ClassName = "Frame",
                            Name = "BossRespawn",
                            Properties = {
                                BackgroundColor3 = Color3.new(0.90196079, 0.90196079, 0.90196079),
                                BorderSizePixel = 0,
                                ClipsDescendants = true,
                                LayoutOrder = 1,
                                Size = UDim2.new(0.25, -6, 1, 0)
                            }
                        },
                        {
                            Attributes = {
                                DonationGenerated = true
                            },
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {
                                        CornerRadius = UDim.new(0, 5)
                                    }
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UIStroke",
                                    Name = "UIStroke",
                                    Properties = {
                                        Thickness = 2
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextLabel",
                                    Name = "Header",
                                    Properties = {
                                        BackgroundColor3 = Color3.new(1, 0.80392158, 0.274509817),
                                        BorderSizePixel = 0,
                                        Font = Enum.Font.GothamBlack,
                                        Size = UDim2.new(1, 0, 0, 29),
                                        Text = "СБРОС СТАТИСТИКИ",
                                        TextColor3 = Color3.new(0.0784313753, 0.0784313753, 0.0784313753),
                                        TextScaled = true,
                                        TextWrapped = true
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {
                                                DonationGenerated = true
                                            },
                                            Children = {
                                                {
                                                    Attributes = {},
                                                    Children = {},
                                                    ClassName = "UITextSizeConstraint",
                                                    Name = "UITextSizeConstraint",
                                                    Properties = {}
                                                },
                                                {
                                                    Attributes = {},
                                                    Children = {},
                                                    ClassName = "UIGradient",
                                                    Name = "UIGradient",
                                                    Properties = {}
                                                }
                                            },
                                            ClassName = "TextLabel",
                                            Name = "FallbackImage",
                                            Properties = {
                                                BackgroundColor3 = Color3.new(0.921568632, 0.921568632, 0.921568632),
                                                Font = Enum.Font.GothamBlack,
                                                Size = UDim2.new(1, 0, 1, 0),
                                                Text = "1 токен",
                                                TextColor3 = Color3.new(0.0588235296, 0.0588235296, 0.0588235296),
                                                TextScaled = true,
                                                TextWrapped = true
                                            }
                                        }
                                    },
                                    ClassName = "Frame",
                                    Name = "ImageHolder",
                                    Properties = {
                                        BackgroundTransparency = 1,
                                        ClipsDescendants = true,
                                        Position = UDim2.new(0, 4, 0, 33),
                                        Size = UDim2.new(1.00000012, -8, 1.07558143, -78)
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UICorner",
                                            Name = "UICorner",
                                            Properties = {
                                                CornerRadius = UDim.new(0, 4)
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UIStroke",
                                            Name = "UIStroke",
                                            Properties = {
                                                Color = Color3.new(0, 0.372549027, 0.137254909),
                                                Thickness = 2
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextButton",
                                    Name = "Buy",
                                    Properties = {
                                        BackgroundColor3 = Color3.new(0, 0.823529422, 0.274509817),
                                        BorderSizePixel = 0,
                                        Position = UDim2.new(0, 0, 1, -32),
                                        Size = UDim2.new(1, 0, 0, 32),
                                        Text = "R$ 75",
                                        TextColor3 = Color3.new(1, 0.90196079, 0.431372553),
                                        TextScaled = true,
                                        TextWrapped = true,
                                        FontFace = Font.new("rbxasset://fonts/families/Montserrat.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
                                        TextSize = 18,
                                        TextStrokeTransparency = 1,
                                        TextYAlignment = Enum.TextYAlignment.Center
                                    }
                                }
                            },
                            ClassName = "Frame",
                            Name = "StatReset",
                            Properties = {
                                BackgroundColor3 = Color3.new(0.90196079, 0.90196079, 0.90196079),
                                BorderSizePixel = 0,
                                ClipsDescendants = true,
                                LayoutOrder = 2,
                                Size = UDim2.new(0.25, -6, 1, 0)
                            }
                        },
                        {
                            Attributes = {
                                DonationGenerated = true
                            },
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {
                                        CornerRadius = UDim.new(0, 5)
                                    }
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UIStroke",
                                    Name = "UIStroke",
                                    Properties = {
                                        Thickness = 2
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextLabel",
                                    Name = "Header",
                                    Properties = {
                                        BackgroundColor3 = Color3.new(1, 0.80392158, 0.274509817),
                                        BorderSizePixel = 0,
                                        Font = Enum.Font.GothamBlack,
                                        Size = UDim2.new(1, 0, 0, 29),
                                        Text = "СМЕНА РАСЫ",
                                        TextColor3 = Color3.new(0.0784313753, 0.0784313753, 0.0784313753),
                                        TextScaled = true,
                                        TextWrapped = true
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {
                                                DonationGenerated = true
                                            },
                                            Children = {
                                                {
                                                    Attributes = {},
                                                    Children = {},
                                                    ClassName = "UITextSizeConstraint",
                                                    Name = "UITextSizeConstraint",
                                                    Properties = {}
                                                },
                                                {
                                                    Attributes = {},
                                                    Children = {},
                                                    ClassName = "UIGradient",
                                                    Name = "UIGradient",
                                                    Properties = {}
                                                }
                                            },
                                            ClassName = "TextLabel",
                                            Name = "FallbackImage",
                                            Properties = {
                                                BackgroundColor3 = Color3.new(0.921568632, 0.921568632, 0.921568632),
                                                Font = Enum.Font.GothamBlack,
                                                Size = UDim2.new(1, 0, 1, 0),
                                                Text = "случайный шанс",
                                                TextColor3 = Color3.new(0.0588235296, 0.0588235296, 0.0588235296),
                                                TextScaled = true,
                                                TextWrapped = true
                                            }
                                        }
                                    },
                                    ClassName = "Frame",
                                    Name = "ImageHolder",
                                    Properties = {
                                        BackgroundTransparency = 1,
                                        ClipsDescendants = true,
                                        Position = UDim2.new(0, 4, 0, 33),
                                        Size = UDim2.new(1.00000012, -8, 1.07558143, -78)
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UICorner",
                                            Name = "UICorner",
                                            Properties = {
                                                CornerRadius = UDim.new(0, 4)
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UIStroke",
                                            Name = "UIStroke",
                                            Properties = {
                                                Color = Color3.new(0, 0.372549027, 0.137254909),
                                                Thickness = 2
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextButton",
                                    Name = "Buy",
                                    Properties = {
                                        BackgroundColor3 = Color3.new(0, 0.823529422, 0.274509817),
                                        BorderSizePixel = 0,
                                        Position = UDim2.new(0, 0, 1, -32),
                                        Size = UDim2.new(1, 0, 0, 32),
                                        Text = "R$ 90",
                                        TextColor3 = Color3.new(1, 0.90196079, 0.431372553),
                                        TextScaled = true,
                                        TextWrapped = true,
                                        FontFace = Font.new("rbxasset://fonts/families/Montserrat.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
                                        TextSize = 18,
                                        TextStrokeTransparency = 1,
                                        TextYAlignment = Enum.TextYAlignment.Center
                                    }
                                }
                            },
                            ClassName = "Frame",
                            Name = "RaceReroll",
                            Properties = {
                                BackgroundColor3 = Color3.new(0.90196079, 0.90196079, 0.90196079),
                                BorderSizePixel = 0,
                                ClipsDescendants = true,
                                LayoutOrder = 3,
                                Size = UDim2.new(0.25, -6, 1, 0)
                            }
                        },
                        {
                            Attributes = {
                                DonationGenerated = true
                            },
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {
                                        CornerRadius = UDim.new(0, 5)
                                    }
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UIStroke",
                                    Name = "UIStroke",
                                    Properties = {
                                        Thickness = 2
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextLabel",
                                    Name = "Header",
                                    Properties = {
                                        BackgroundColor3 = Color3.new(1, 0.80392158, 0.274509817),
                                        BorderSizePixel = 0,
                                        Font = Enum.Font.GothamBlack,
                                        Size = UDim2.new(1, 0, 0, 29),
                                        Text = "LUCKY CASES",
                                        TextColor3 = Color3.new(0.0784313753, 0.0784313753, 0.0784313753),
                                        TextScaled = true,
                                        TextWrapped = true
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {
                                                DonationGenerated = true
                                            },
                                            Children = {
                                                {
                                                    Attributes = {},
                                                    Children = {},
                                                    ClassName = "UITextSizeConstraint",
                                                    Name = "UITextSizeConstraint",
                                                    Properties = {}
                                                },
                                                {
                                                    Attributes = {},
                                                    Children = {},
                                                    ClassName = "UIGradient",
                                                    Name = "UIGradient",
                                                    Properties = {}
                                                }
                                            },
                                            ClassName = "TextLabel",
                                            Name = "FallbackImage",
                                            Properties = {
                                                BackgroundColor3 = Color3.new(0.921568632, 0.921568632, 0.921568632),
                                                Font = Enum.Font.GothamBlack,
                                                Size = UDim2.new(1, 0, 1, 0),
                                                Text = "3 кейса",
                                                TextColor3 = Color3.new(0.0588235296, 0.0588235296, 0.0588235296),
                                                TextScaled = true,
                                                TextWrapped = true
                                            }
                                        }
                                    },
                                    ClassName = "Frame",
                                    Name = "ImageHolder",
                                    Properties = {
                                        BackgroundTransparency = 1,
                                        ClipsDescendants = true,
                                        Position = UDim2.new(0, 4, 0, 33),
                                        Size = UDim2.new(1.00000012, -8, 1.07558143, -78)
                                    }
                                },
                                {
                                    Attributes = {
                                        DonationGenerated = true
                                    },
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UICorner",
                                            Name = "UICorner",
                                            Properties = {
                                                CornerRadius = UDim.new(0, 4)
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UIStroke",
                                            Name = "UIStroke",
                                            Properties = {
                                                Color = Color3.new(0, 0.372549027, 0.137254909),
                                                Thickness = 2
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        }
                                    },
                                    ClassName = "TextButton",
                                    Name = "Buy",
                                    Properties = {
                                        BackgroundColor3 = Color3.new(0, 0.823529422, 0.274509817),
                                        BorderSizePixel = 0,
                                        Position = UDim2.new(0, 0, 1, -32),
                                        Size = UDim2.new(1, 0, 0, 32),
                                        Text = "R$ 149",
                                        TextColor3 = Color3.new(1, 0.90196079, 0.431372553),
                                        TextScaled = true,
                                        TextWrapped = true,
                                        FontFace = Font.new("rbxasset://fonts/families/Montserrat.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
                                        TextSize = 18,
                                        TextStrokeTransparency = 1,
                                        TextYAlignment = Enum.TextYAlignment.Center
                                    }
                                }
                            },
                            ClassName = "Frame",
                            Name = "LuckyCases",
                            Properties = {
                                BackgroundColor3 = Color3.new(0.90196079, 0.90196079, 0.90196079),
                                BorderSizePixel = 0,
                                ClipsDescendants = true,
                                LayoutOrder = 4,
                                Size = UDim2.new(0.25, -6, 1, 0)
                            }
                        }
                    },
                    ClassName = "Frame",
                    Name = "GOODS",
                    Properties = {
                        BackgroundTransparency = 1,
                        Size = UDim2.new(1, -10, 0, 172),
                        Visible = false
                    }
                },
                {
                    Attributes = {
                        DonationGenerated = true
                    },
                    Children = {
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UITextSizeConstraint",
                            Name = "UITextSizeConstraint",
                            Properties = {}
                        }
                    },
                    ClassName = "TextLabel",
                    Name = "LIFETIMESUBSCRIPTIONSTitle",
                    Properties = {
                        BackgroundTransparency = 1,
                        Font = Enum.Font.Gotham,
                        LayoutOrder = 4,
                        Position = UDim2.new(0, 0, 0.692504406, 0),
                        Size = UDim2.new(1, 0, 0.191008136, 0),
                        Text = "",
                        TextColor3 = Color3.new(0.960784316, 0.960784316, 0.960784316),
                        Visible = false,
                        TextScaled = true,
                        TextWrapped = true,
                        TextXAlignment = Enum.TextXAlignment.Left
                    }
                }
            },
            ClassName = "ScrollingFrame",
            Name = "ScrollFrame",
            Properties = {
                AnchorPoint = Vector2.new(1, 0.5),
                AutomaticCanvasSize = Enum.AutomaticSize.Y,
                BackgroundColor3 = Color3.new(0, 0, 0),
                BackgroundTransparency = 0.5,
                BorderColor3 = Color3.new(0, 0, 0),
                BorderSizePixel = 0,
                CanvasSize = UDim2.new(0, 0, 0, 0),
                Position = UDim2.new(1.00285208, 0, 0.491856843, 0),
                ScrollBarThickness = 8,
                Selectable = false,
                Size = UDim2.new(0.999324322, 0, 0.983713567, 0)
            }
        }
    },
    ClassName = "Frame",
    Name = "Gold",
    Properties = {
        AnchorPoint = Vector2.new(1, 0.5),
        BackgroundColor3 = Color3.new(0, 0, 0),
        BackgroundTransparency = 0.5,
        BorderColor3 = Color3.new(0, 0, 0),
        BorderSizePixel = 0,
        ClipsDescendants = true,
        Position = UDim2.new(0.788063347, 0, 0.576163054, 0),
        Size = UDim2.new(0.773510516, 0, 0.815101027, 0),
        Visible = false
    }
};