-- ClassName: ModuleScript
-- Roblox Path: game.ReplicatedStorage.Framework.GeneratedUI.GuiSpecParts.Gui_Shop_21

-- Decompiled with Potassium's decompiler.

return {
    Attributes = {},
    Children = {
        require(script.Parent.Gui_Shop_UICorner_3),
        require(script.Parent.Gui_Shop_ModDefult_4),
        require(script.Parent.Gui_Shop_title_5),
        require(script.Parent.Gui_Shop_GoldValue_6),
        require(script.Parent.Gui_Shop_Skins_7),
        require(script.Parent.Gui_Shop_Select_8),
        require(script.Parent.Gui_Shop_UIAspectRatioConstraint_9),
        require(script.Parent.Gui_Shop_Close_10),
        require(script.Parent.Gui_Shop_Abilities_11),
        require(script.Parent.Gui_Shop_Accessories_12),
        require(script.Parent.Gui_Shop_Cases_13),
        require(script.Parent.Gui_Shop_Bots_14),
        require(script.Parent.Gui_Shop_UISizeConstraint_15),
        require(script.Parent.Gui_Shop_p_16),
        require(script.Parent.Gui_Shop_Title_17),
        require(script.Parent.Gui_Shop_Gold_18),
        require(script.Parent.Gui_Shop_Avatar_19),
        require(script.Parent.Gui_Shop_SelectColor_20)
    },
    ClassName = "Frame",
    Name = "Shop",
    Properties = {
        Active = true,
        AnchorPoint = Vector2.new(0.5, 0.5),
        BackgroundColor3 = Color3.new(0.278431386, 0.278431386, 0.278431386),
        BorderColor3 = Color3.new(0, 0, 0),
        BorderSizePixel = 0,
        Position = UDim2.new(0.5, 0, 0.540000021, 0),
        Size = UDim2.new(0.567281783, 0, 0.718128681, 0),
        Visible = false,
        ZIndex = 10
    }
};