-- ClassName: ModuleScript
-- Roblox Path: game.ReplicatedStorage.Framework.GeneratedUI.GuiSpecParts.Gui_Shop_Close_10

-- Decompiled with Potassium's decompiler.

return {
    Attributes = {},
    Children = {
        {
            Attributes = {},
            Children = {},
            ClassName = "UICorner",
            Name = "UICorner",
            Properties = {}
        },
        {
            Attributes = {},
            Children = {},
            ClassName = "UITextSizeConstraint",
            Name = "UITextSizeConstraint",
            Properties = {}
        },
        {
            Attributes = {},
            Children = {},
            ClassName = "UIAspectRatioConstraint",
            Name = "UIAspectRatioConstraint",
            Properties = {}
        },
        {
            Attributes = {},
            Children = {},
            ClassName = "UISizeConstraint",
            Name = "UISizeConstraint",
            Properties = {
                MinSize = Vector2.new(40, 40)
            }
        }
    },
    ClassName = "TextButton",
    Name = "Close",
    Properties = {
        Active = false,
        AnchorPoint = Vector2.new(1, 0),
        BackgroundColor3 = Color3.new(0.666666687, 0, 0),
        BorderColor3 = Color3.new(0, 0, 0),
        BorderSizePixel = 0,
        Font = Enum.Font.GothamBold,
        LayoutOrder = 2,
        Position = UDim2.new(1, 0, 0, 0),
        Selectable = false,
        Size = UDim2.new(0.0358314589, 0, 0.0719888806, 0),
        Text = "X",
        TextColor3 = Color3.new(1, 1, 1),
        TextScaled = true,
        TextWrapped = true
    }
};