-- ClassName: ModuleScript
-- Roblox Path: game.ReplicatedStorage.Framework.GeneratedUI.GuiSpecParts.Gui_Servers_1

-- Decompiled with Potassium's decompiler.

return {
    Attributes = {},
    Children = {
        {
            Attributes = {},
            Children = {},
            ClassName = "UIAspectRatioConstraint",
            Name = "UIAspectRatioConstraint",
            Properties = {
                AspectRatio = 1.1895636320114136
            }
        },
        {
            Attributes = {},
            Children = {},
            ClassName = "UISizeConstraint",
            Name = "UISizeConstraint",
            Properties = {
                MaxSize = Vector2.new(800, 800),
                MinSize = Vector2.new(400, 400)
            }
        },
        {
            Attributes = {},
            Children = {},
            ClassName = "UICorner",
            Name = "UICorner",
            Properties = {}
        },
        {
            Attributes = {},
            Children = {
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UICorner",
                    Name = "UICorner",
                    Properties = {}
                },
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UIListLayout",
                    Name = "UIListLayout",
                    Properties = {
                        Padding = UDim.new(0, 2),
                        SortOrder = Enum.SortOrder.LayoutOrder
                    }
                },
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UIPadding",
                    Name = "UIPadding",
                    Properties = {
                        PaddingBottom = UDim.new(0, 4),
                        PaddingLeft = UDim.new(0, 4),
                        PaddingRight = UDim.new(0, 4),
                        PaddingTop = UDim.new(0, 4)
                    }
                },
                {
                    Attributes = {},
                    Children = {
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UICorner",
                            Name = "UICorner",
                            Properties = {
                                CornerRadius = UDim.new(0, 6)
                            }
                        },
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UITextSizeConstraint",
                            Name = "UITextSizeConstraint",
                            Properties = {}
                        },
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {}
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UITextSizeConstraint",
                                    Name = "UITextSizeConstraint",
                                    Properties = {}
                                }
                            },
                            ClassName = "TextLabel",
                            Name = "Menu",
                            Properties = {
                                AnchorPoint = Vector2.new(1, 0),
                                BackgroundColor3 = Color3.new(0.443137288, 0.443137288, 0.443137288),
                                BackgroundTransparency = 1,
                                BorderColor3 = Color3.new(0, 0, 0),
                                BorderSizePixel = 0,
                                LayoutOrder = 1,
                                Position = UDim2.new(0.0199999996, 0, 0, 0),
                                Size = UDim2.new(0.479999989, 0, 1, 0),
                                Text = "Ukraine",
                                TextColor3 = Color3.new(1, 1, 1),
                                TextScaled = true,
                                TextWrapped = true,
                                TextXAlignment = Enum.TextXAlignment.Left,
                                Visible = false
                            }
                        },
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {}
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UITextSizeConstraint",
                                    Name = "UITextSizeConstraint",
                                    Properties = {}
                                }
                            },
                            ClassName = "TextLabel",
                            Name = "Menu",
                            Properties = {
                                AnchorPoint = Vector2.new(1, 0),
                                BackgroundColor3 = Color3.new(0.443137288, 0.443137288, 0.443137288),
                                BackgroundTransparency = 1,
                                BorderColor3 = Color3.new(0, 0, 0),
                                BorderSizePixel = 0,
                                LayoutOrder = 1,
                                Position = UDim2.new(0.769999981, 0, 0, 0),
                                Size = UDim2.new(0.209999993, 0, 1, 0),
                                Text = "4/16",
                                TextColor3 = Color3.new(1, 1, 1),
                                TextScaled = true,
                                TextWrapped = true,
                                Visible = false
                            }
                        },
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {}
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UITextSizeConstraint",
                                    Name = "UITextSizeConstraint",
                                    Properties = {}
                                }
                            },
                            ClassName = "TextLabel",
                            Name = "LegacyMassValue",
                            Properties = {
                                AnchorPoint = Vector2.new(1, 0),
                                BackgroundColor3 = Color3.new(0.443137288, 0.443137288, 0.443137288),
                                BackgroundTransparency = 1,
                                BorderColor3 = Color3.new(0, 0, 0),
                                BorderSizePixel = 0,
                                LayoutOrder = 1,
                                Position = UDim2.new(0.560000002, 0, 0, 0),
                                Size = UDim2.new(0.170000002, 0, 1, 0),
                                Text = "0",
                                TextColor3 = Color3.new(1, 1, 1),
                                TextScaled = true,
                                TextWrapped = true,
                                Visible = false
                            }
                        },
                        {
                            Attributes = {
                                ModeValueLabel = true
                            },
                            Children = {},
                            ClassName = "TextLabel",
                            Name = "RegionValue",
                            Properties = {
                                BackgroundTransparency = 1,
                                BorderSizePixel = 0,
                                Font = Enum.Font.GothamMedium,
                                Position = UDim2.new(0.0199999996, 0, 0, 0),
                                Size = UDim2.new(0.439999998, 0, 1, 0),
                                TextColor3 = Color3.new(1, 1, 1),
                                TextSize = 16,
                                TextTruncate = Enum.TextTruncate.AtEnd,
                                TextXAlignment = Enum.TextXAlignment.Left,
                                ZIndex = 3
                            }
                        },
                        {
                            Attributes = {
                                ModeValueLabel = true
                            },
                            Children = {},
                            ClassName = "TextLabel",
                            Name = "MassValue",
                            Properties = {
                                BackgroundTransparency = 1,
                                BorderSizePixel = 0,
                                Font = Enum.Font.GothamMedium,
                                Position = UDim2.new(0.49000001, 0, 0, 0),
                                Size = UDim2.new(0.200000003, 0, 1, 0),
                                TextColor3 = Color3.new(1, 1, 1),
                                TextSize = 16,
                                TextTruncate = Enum.TextTruncate.AtEnd,
                                ZIndex = 3
                            }
                        },
                        {
                            Attributes = {
                                ModeValueLabel = true
                            },
                            Children = {},
                            ClassName = "TextLabel",
                            Name = "PlayersValue",
                            Properties = {
                                BackgroundTransparency = 1,
                                BorderSizePixel = 0,
                                Font = Enum.Font.GothamMedium,
                                Position = UDim2.new(0.730000019, 0, 0, 0),
                                Size = UDim2.new(0.25, 0, 1, 0),
                                TextColor3 = Color3.new(1, 1, 1),
                                TextSize = 16,
                                TextTruncate = Enum.TextTruncate.AtEnd,
                                ZIndex = 3
                            }
                        }
                    },
                    ClassName = "Frame",
                    Name = "Server",
                    Properties = {
                        BackgroundColor3 = Color3.new(0.443137258, 0.443137258, 0.443137258),
                        BorderColor3 = Color3.new(0, 0, 0),
                        BorderSizePixel = 0,
                        ClipsDescendants = true,
                        LayoutOrder = 1,
                        Size = UDim2.new(1, -8, 0, 54),
                        Visible = false
                    }
                }
            },
            ClassName = "ScrollingFrame",
            Name = "ServersScrolling",
            Properties = {
                AutomaticCanvasSize = Enum.AutomaticSize.Y,
                BackgroundColor3 = Color3.new(0, 0, 0),
                BackgroundTransparency = 1,
                BorderColor3 = Color3.new(0, 0, 0),
                BorderSizePixel = 0,
                CanvasSize = UDim2.new(0, 0, 0, 0),
                Position = UDim2.new(0, 0, 0.189999998, 0),
                ScrollBarThickness = 7,
                Selectable = false,
                Size = UDim2.new(1, 0, 0.779999971, 0)
            }
        },
        {
            Attributes = {},
            Children = {
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UICorner",
                    Name = "UICorner",
                    Properties = {}
                },
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UITextSizeConstraint",
                    Name = "UITextSizeConstraint",
                    Properties = {}
                },
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UITextSizeConstraint",
                    Name = "ModeServerTitleSize",
                    Properties = {}
                }
            },
            ClassName = "TextLabel",
            Name = "ModDefult",
            Properties = {
                BackgroundColor3 = Color3.new(0.172549024, 0.172549024, 0.172549024),
                BackgroundTransparency = 1,
                BorderColor3 = Color3.new(0, 0, 0),
                BorderSizePixel = 0,
                Font = Enum.Font.GothamBold,
                LayoutOrder = 2,
                Position = UDim2.new(0.310000002, 0, 0.00999999978, 0),
                Size = UDim2.new(0.379999995, 0, 0.0649999976, 0),
                Text = "Defult",
                TextColor3 = Color3.new(1, 1, 1),
                TextSize = 22,
                TextTruncate = Enum.TextTruncate.AtEnd,
                ZIndex = 5
            }
        },
        {
            Attributes = {},
            Children = {
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UICorner",
                    Name = "UICorner",
                    Properties = {}
                },
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UITextSizeConstraint",
                    Name = "UITextSizeConstraint",
                    Properties = {}
                }
            },
            ClassName = "TextLabel",
            Name = "title",
            Properties = {
                AnchorPoint = Vector2.new(1, 0),
                BackgroundColor3 = Color3.new(0.172549024, 0.172549024, 0.172549024),
                BackgroundTransparency = 1,
                BorderColor3 = Color3.new(0, 0, 0),
                BorderSizePixel = 0,
                Font = Enum.Font.Gotham,
                LayoutOrder = 2,
                Position = UDim2.new(0.75999999, 0, 0.0850000009, 0),
                Size = UDim2.new(0.200000003, 0, 0.0700000003, 0),
                Text = "Players",
                TextColor3 = Color3.new(1, 1, 1),
                TextScaled = true,
                TextWrapped = true,
                Visible = false
            }
        },
        {
            Attributes = {},
            Children = {
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UICorner",
                    Name = "UICorner",
                    Properties = {}
                },
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UITextSizeConstraint",
                    Name = "UITextSizeConstraint",
                    Properties = {}
                }
            },
            ClassName = "TextLabel",
            Name = "title",
            Properties = {
                AnchorPoint = Vector2.new(1, 0),
                BackgroundColor3 = Color3.new(0.172549024, 0.172549024, 0.172549024),
                BackgroundTransparency = 1,
                BorderColor3 = Color3.new(0, 0, 0),
                BorderSizePixel = 0,
                Font = Enum.Font.Gotham,
                LayoutOrder = 2,
                Position = UDim2.new(0.0399999991, 0, 0.0850000009, 0),
                Size = UDim2.new(0.340000004, 0, 0.0700000003, 0),
                Text = "Region",
                TextColor3 = Color3.new(1, 1, 1),
                TextScaled = true,
                TextWrapped = true,
                TextXAlignment = Enum.TextXAlignment.Left,
                Visible = false
            }
        },
        {
            Attributes = {},
            Children = {},
            ClassName = "TextButton",
            Name = "p",
            Properties = {
                AnchorPoint = Vector2.new(0.5, 0.5),
                AutoButtonColor = false,
                BackgroundColor3 = Color3.new(1, 1, 1),
                BackgroundTransparency = 1,
                BorderColor3 = Color3.new(0, 0, 0),
                BorderSizePixel = 0,
                Font = Enum.Font.SourceSans,
                Position = UDim2.new(0.5, 0, 0.5, 0),
                Size = UDim2.new(1, 0, 1, 0),
                Text = "",
                TextColor3 = Color3.new(0, 0, 0),
                TextSize = 14,
                ZIndex = -100
            }
        },
        {
            Attributes = {},
            Children = {
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UITextSizeConstraint",
                    Name = "UITextSizeConstraint",
                    Properties = {}
                },
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UITextSizeConstraint",
                    Name = "ModeServerStatusSize",
                    Properties = {}
                }
            },
            ClassName = "TextLabel",
            Name = "ModeServersStatus",
            Properties = {
                BackgroundTransparency = 1,
                BorderSizePixel = 0,
                Font = Enum.Font.Gotham,
                Position = UDim2.new(0.0250000004, 0, 0.0250000004, 0),
                Size = UDim2.new(0.239999995, 0, 0.0450000018, 0),
                Text = "",
                TextColor3 = Color3.new(1, 1, 1),
                TextSize = 13,
                TextTruncate = Enum.TextTruncate.AtEnd,
                TextXAlignment = Enum.TextXAlignment.Left,
                ZIndex = 5
            }
        },
        {
            Attributes = {},
            Children = {
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UITextSizeConstraint",
                    Name = "UITextSizeConstraint",
                    Properties = {}
                }
            },
            ClassName = "TextLabel",
            Name = "MassTitle",
            Properties = {
                BackgroundTransparency = 1,
                Position = UDim2.new(0.550000012, 0, 0.0850000009, 0),
                Size = UDim2.new(0.180000007, 0, 0.0700000003, 0),
                Text = "Mass",
                TextColor3 = Color3.new(1, 1, 1),
                TextScaled = true,
                TextWrapped = true,
                Visible = false
            }
        },
        {
            Attributes = {},
            Children = {
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UITextSizeConstraint",
                    Name = "ModeServerHeaderSize",
                    Properties = {}
                }
            },
            ClassName = "TextLabel",
            Name = "ModeServersRegionHeader",
            Properties = {
                BackgroundTransparency = 1,
                BorderSizePixel = 0,
                Font = Enum.Font.GothamMedium,
                Position = UDim2.new(0.0299999993, 0, 0.100000001, 0),
                Size = UDim2.new(0.419999987, 0, 0.0599999987, 0),
                Text = "Region",
                TextColor3 = Color3.new(1, 1, 1),
                TextSize = 22,
                TextTruncate = Enum.TextTruncate.AtEnd,
                TextXAlignment = Enum.TextXAlignment.Left,
                ZIndex = 5
            }
        },
        {
            Attributes = {},
            Children = {
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UITextSizeConstraint",
                    Name = "ModeServerHeaderSize",
                    Properties = {}
                }
            },
            ClassName = "TextLabel",
            Name = "ModeServersMassHeader",
            Properties = {
                BackgroundTransparency = 1,
                BorderSizePixel = 0,
                Font = Enum.Font.GothamMedium,
                Position = UDim2.new(0.5, 0, 0.100000001, 0),
                Size = UDim2.new(0.180000007, 0, 0.0599999987, 0),
                Text = "Mass",
                TextColor3 = Color3.new(1, 1, 1),
                TextSize = 22,
                TextTruncate = Enum.TextTruncate.AtEnd,
                ZIndex = 5
            }
        },
        {
            Attributes = {},
            Children = {
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UITextSizeConstraint",
                    Name = "ModeServerHeaderSize",
                    Properties = {}
                }
            },
            ClassName = "TextLabel",
            Name = "ModeServersPlayersHeader",
            Properties = {
                BackgroundTransparency = 1,
                BorderSizePixel = 0,
                Font = Enum.Font.GothamMedium,
                Position = UDim2.new(0.720000029, 0, 0.100000001, 0),
                Size = UDim2.new(0.25999999, 0, 0.0599999987, 0),
                Text = "Players",
                TextColor3 = Color3.new(1, 1, 1),
                TextSize = 22,
                TextTruncate = Enum.TextTruncate.AtEnd,
                ZIndex = 5
            }
        },
        {
            Attributes = {},
            Children = {
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UITextSizeConstraint",
                    Name = "ModeServersCloseSize",
                    Properties = {}
                },
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UICorner",
                    Name = "UICorner",
                    Properties = {
                        CornerRadius = UDim.new(0, 6)
                    }
                }
            },
            ClassName = "TextButton",
            Name = "ModeServersClose",
            Properties = {
                AnchorPoint = Vector2.new(1, 0),
                BackgroundColor3 = Color3.new(0.607843161, 0.227450982, 0.227450982),
                BorderSizePixel = 0,
                Font = Enum.Font.GothamBold,
                Position = UDim2.new(1, -8, 0, 6),
                Size = UDim2.new(0, 30, 0, 24),
                Text = "X",
                TextColor3 = Color3.new(1, 1, 1),
                TextScaled = true,
                TextWrapped = true,
                ZIndex = 6
            }
        },
        {
            Attributes = {},
            Children = {
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UITextSizeConstraint",
                    Name = "EditCustomModeButtonSize",
                    Properties = {}
                },
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UICorner",
                    Name = "UICorner",
                    Properties = {
                        CornerRadius = UDim.new(0, 6)
                    }
                }
            },
            ClassName = "TextButton",
            Name = "EditCustomModeButton",
            Properties = {
                AnchorPoint = Vector2.new(1, 0),
                BackgroundColor3 = Color3.new(1, 0.333333343, 0),
                BorderSizePixel = 0,
                Font = Enum.Font.GothamBold,
                Position = UDim2.new(1, -46, 0, 6),
                Size = UDim2.new(0, 64, 0, 24),
                Text = "Edit",
                TextColor3 = Color3.new(1, 1, 1),
                TextScaled = true,
                TextWrapped = true,
                Visible = false,
                ZIndex = 6
            }
        }
    },
    ClassName = "Frame",
    Name = "Servers",
    Properties = {
        AnchorPoint = Vector2.new(0.5, 0.5),
        BackgroundColor3 = Color3.new(0.290196091, 0.290196091, 0.290196091),
        BackgroundTransparency = 0.05000000074505806,
        BorderColor3 = Color3.new(0, 0, 0),
        BorderSizePixel = 0,
        Position = UDim2.new(0.499484032, 0, 0.499415159, 0),
        Size = UDim2.new(0.376879305, 0, 0.718128681, 0),
        Visible = false,
        ZIndex = 2
    }
};