-- ClassName: ModuleScript
-- Roblox Path: game.ReplicatedStorage.Framework.GeneratedUI.GuiSpecParts.Gui_Shop_ModDefult_4

-- Decompiled with Potassium's decompiler.

return {
    Attributes = {},
    Children = {
        {
            Attributes = {},
            Children = {},
            ClassName = "UICorner",
            Name = "UICorner",
            Properties = {}
        }
    },
    ClassName = "TextLabel",
    Name = "ModDefult",
    Properties = {
        AnchorPoint = Vector2.new(1, 0),
        BackgroundColor3 = Color3.new(0.172549024, 0.172549024, 0.172549024),
        BackgroundTransparency = 1,
        BorderColor3 = Color3.new(0, 0, 0),
        BorderSizePixel = 0,
        Font = Enum.Font.GothamBold,
        LayoutOrder = 2,
        Position = UDim2.new(1.00055265, 0, 0.171009779, 0),
        Size = UDim2.new(0.208850667, 0, 0.121381231, 0),
        Text = "Shop",
        TextColor3 = Color3.new(1, 1, 1),
        TextScaled = true,
        TextWrapped = true
    }
};