-- ClassName: ModuleScript
-- Roblox Path: game.ReplicatedStorage.Framework.GeneratedUI.GuiSpecParts.Gui_Shop_UISizeConstraint_15

-- Decompiled with Potassium's decompiler.

return {
    Attributes = {},
    Children = {},
    ClassName = "UISizeConstraint",
    Name = "UISizeConstraint",
    Properties = {
        MaxSize = Vector2.new(1150, 800),
        MinSize = Vector2.new(520, 450)
    }
};