-- ClassName: ModuleScript
-- Roblox Path: game.ReplicatedStorage.Framework.GeneratedUI.GuiSpecParts.Gui_Shop_p_16

-- Decompiled with Potassium's decompiler.

return {
    Attributes = {},
    Children = {},
    ClassName = "TextButton",
    Name = "p",
    Properties = {
        AnchorPoint = Vector2.new(0.5, 0.5),
        AutoButtonColor = false,
        BackgroundColor3 = Color3.new(1, 1, 1),
        BackgroundTransparency = 1,
        BorderColor3 = Color3.new(0, 0, 0),
        BorderSizePixel = 0,
        Font = Enum.Font.SourceSans,
        Position = UDim2.new(0.5, 0, 0.5, 0),
        Size = UDim2.new(1, 0, 1, 0),
        Text = "",
        TextColor3 = Color3.new(0, 0, 0),
        TextSize = 14,
        ZIndex = -100
    }
};