-- ClassName: ModuleScript
-- Roblox Path: game.ReplicatedStorage.Framework.GeneratedUI.GuiSpecParts.Gui_Shop_SelectColor_20

-- Decompiled with Potassium's decompiler.

return {
    Attributes = {},
    Children = {
        {
            Attributes = {},
            Children = {},
            ClassName = "UICorner",
            Name = "UICorner",
            Properties = {}
        },
        {
            Attributes = {},
            Children = {},
            ClassName = "UITextSizeConstraint",
            Name = "UITextSizeConstraint",
            Properties = {}
        }
    },
    ClassName = "TextButton",
    Name = "SelectColor",
    Properties = {
        Active = false,
        AnchorPoint = Vector2.new(1, 0),
        BackgroundColor3 = Color3.new(0.533333361, 0.533333361, 0.533333361),
        BorderColor3 = Color3.new(0, 0, 0),
        BorderSizePixel = 0,
        Font = Enum.Font.GothamBold,
        LayoutOrder = 2,
        Position = UDim2.new(0.980928183, 0, 0.829749525, 0),
        Selectable = false,
        Size = UDim2.new(0.163801879, 0, 0.0475589149, 0),
        Text = "Select Color",
        TextColor3 = Color3.new(0.972549081, 0.972549081, 0.972549081),
        TextScaled = true,
        TextWrapped = true
    }
};