-- ClassName: ModuleScript
-- Roblox Path: game.ReplicatedStorage.Framework.GeneratedUI.GuiSpecParts.Gui_Menu_2

-- Decompiled with Potassium's decompiler.

return {
    Attributes = {},
    Children = {
        {
            Attributes = {},
            Children = {},
            ClassName = "UIAspectRatioConstraint",
            Name = "UIAspectRatioConstraint",
            Properties = {
                AspectRatio = 2.395209550857544
            }
        },
        {
            Attributes = {},
            Children = {},
            ClassName = "UICorner",
            Name = "UICorner",
            Properties = {}
        },
        {
            Attributes = {},
            Children = {},
            ClassName = "UISizeConstraint",
            Name = "UISizeConstraint",
            Properties = {
                MaxSize = Vector2.new(1200, 1200)
            }
        },
        {
            Attributes = {},
            Children = {
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UICorner",
                    Name = "UICorner",
                    Properties = {}
                },
                {
                    Attributes = {},
                    Children = {
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UICorner",
                            Name = "UICorner",
                            Properties = {
                                CornerRadius = UDim.new(0, 8)
                            }
                        },
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UITextSizeConstraint",
                            Name = "UITextSizeConstraint",
                            Properties = {
                                MinTextSize = 1,
                                MaxTextSize = 30
                            }
                        }
                    },
                    ClassName = "TextButton",
                    Name = "Play",
                    Properties = {
                        Active = false,
                        AnchorPoint = Vector2.new(1, 0),
                        BackgroundColor3 = Color3.fromRGB(255, 85, 0),
                        BorderColor3 = Color3.new(0, 0, 0),
                        BorderSizePixel = 0,
                        Position = UDim2.new(0.376898259, 0, 0.161732689, 0),
                        Selectable = false,
                        Size = UDim2.new(0.294964045, 0, 0.0838323385, 0),
                        Text = "Play",
                        TextColor3 = Color3.new(1, 1, 1),
                        TextScaled = true,
                        TextWrapped = true,
                        BackgroundTransparency = 0,
                        SizeConstraint = Enum.SizeConstraint.RelativeXY,
                        ZIndex = 1,
                        Visible = true,
                        FontFace = Font.new("rbxasset://fonts/families/Montserrat.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
                        TextSize = 8,
                        TextStrokeColor3 = Color3.new(0, 0, 0),
                        TextStrokeTransparency = 1,
                        TextTransparency = 0,
                        TextXAlignment = Enum.TextXAlignment.Center,
                        TextYAlignment = Enum.TextYAlignment.Center,
                        LineHeight = 1
                    }
                },
                {
                    Attributes = {},
                    Children = {
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UICorner",
                            Name = "UICorner",
                            Properties = {}
                        },
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UITextSizeConstraint",
                            Name = "UITextSizeConstraint",
                            Properties = {}
                        }
                    },
                    ClassName = "TextBox",
                    Name = "Nickname",
                    Properties = {
                        Active = false,
                        AnchorPoint = Vector2.new(1, 0),
                        BackgroundColor3 = Color3.new(0, 0, 0),
                        BackgroundTransparency = 0.75,
                        BorderColor3 = Color3.new(0, 0, 0),
                        BorderSizePixel = 0,
                        ClearTextOnFocus = false,
                        Font = Enum.Font.GothamBold,
                        PlaceholderColor3 = Color3.new(0.699999988, 0.699999988, 0.699999988),
                        PlaceholderText = "Nickname",
                        Position = UDim2.new(0.693445206, 0, 0.0599362813, 0),
                        Selectable = false,
                        Size = UDim2.new(0.611510813, 0, 0.0838323385, 0),
                        Text = "",
                        TextColor3 = Color3.new(1, 1, 1),
                        TextScaled = true,
                        TextWrapped = true
                    }
                },
                {
                    Attributes = {},
                    Children = {
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UICorner",
                            Name = "UICorner",
                            Properties = {
                                CornerRadius = UDim.new(0, 8)
                            }
                        },
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UITextSizeConstraint",
                            Name = "UITextSizeConstraint",
                            Properties = {
                                MinTextSize = 1,
                                MaxTextSize = 30
                            }
                        }
                    },
                    ClassName = "TextButton",
                    Name = "Spectate",
                    Properties = {
                        Active = false,
                        AnchorPoint = Vector2.new(1, 0),
                        BackgroundColor3 = Color3.fromRGB(255, 117, 82),
                        BorderColor3 = Color3.new(0, 0, 0),
                        BorderSizePixel = 0,
                        Position = UDim2.new(0.693445027, 0, 0.161732689, 0),
                        Selectable = false,
                        Size = UDim2.new(0.294999987, 0, 0.0839999989, 0),
                        Text = "Spectate",
                        TextColor3 = Color3.new(1, 1, 1),
                        TextScaled = true,
                        TextWrapped = true,
                        BackgroundTransparency = 0,
                        SizeConstraint = Enum.SizeConstraint.RelativeXY,
                        ZIndex = 1,
                        Visible = true,
                        FontFace = Font.new("rbxasset://fonts/families/Montserrat.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
                        TextSize = 8,
                        TextStrokeColor3 = Color3.new(0, 0, 0),
                        TextStrokeTransparency = 1,
                        TextTransparency = 0,
                        TextXAlignment = Enum.TextXAlignment.Center,
                        TextYAlignment = Enum.TextYAlignment.Center,
                        LineHeight = 1
                    }
                },
                {
                    Attributes = {},
                    Children = {
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UICorner",
                            Name = "UICorner",
                            Properties = {
                                CornerRadius = UDim.new(1, 0)
                            }
                        },
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UITextSizeConstraint",
                            Name = "UITextSizeConstraint",
                            Properties = {}
                        },
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UIAspectRatioConstraint",
                            Name = "UIAspectRatioConstraint",
                            Properties = {}
                        },
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {}
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UITextSizeConstraint",
                                    Name = "UITextSizeConstraint",
                                    Properties = {}
                                }
                            },
                            ClassName = "TextLabel",
                            Name = "q",
                            Properties = {
                                AnchorPoint = Vector2.new(0.5, 0.5),
                                BackgroundColor3 = Color3.new(1, 0.333333343, 0),
                                BackgroundTransparency = 1,
                                BorderColor3 = Color3.new(0, 0, 0),
                                BorderSizePixel = 0,
                                Font = Enum.Font.GothamBold,
                                Position = UDim2.new(0.5, 0, 0.5, 0),
                                Size = UDim2.new(1, 0, 1, 0),
                                Text = "Skins",
                                TextColor3 = Color3.new(1, 0.333333343, 0),
                                TextScaled = true,
                                TextStrokeTransparency = 0.5,
                                TextWrapped = true
                            }
                        }
                    },
                    ClassName = "ImageButton",
                    Name = "Avatar",
                    Properties = {
                        Active = false,
                        AnchorPoint = Vector2.new(1, 0),
                        BackgroundColor3 = Color3.new(0.380392194, 0.380392194, 0.380392194),
                        BorderColor3 = Color3.new(0, 0, 0),
                        BorderSizePixel = 0,
                        Position = UDim2.new(0.959632277, 0, 0.0599362813, 0),
                        Selectable = false,
                        Size = UDim2.new(0.220623523, 0, 0.183632731, 0)
                    }
                }
            },
            ClassName = "Frame",
            Name = "Center",
            Properties = {
                AnchorPoint = Vector2.new(0.5, 0.5),
                BackgroundColor3 = Color3.new(0, 0, 0),
                BackgroundTransparency = 0.5,
                BorderColor3 = Color3.new(0, 0, 0),
                BorderSizePixel = 0,
                Position = UDim2.new(0.5, 0, 0.5, 0),
                Size = UDim2.new(0.308660239, 0, 1, 0)
            }
        },
        {
            Attributes = {},
            Children = {
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UICorner",
                    Name = "UICorner",
                    Properties = {}
                },
                {
                    Attributes = {},
                    Children = {
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UIStroke",
                                    Name = "UIStroke",
                                    Properties = {
                                        Thickness = 1.5,
                                        Transparency = 0.5
                                    }
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UITextSizeConstraint",
                                    Name = "UITextSizeConstraint",
                                    Properties = {}
                                }
                            },
                            ClassName = "TextLabel",
                            Name = "Amount",
                            Properties = {
                                AnchorPoint = Vector2.new(0, 0.5),
                                AutomaticSize = Enum.AutomaticSize.X,
                                BackgroundColor3 = Color3.new(1, 1, 1),
                                BackgroundTransparency = 1,
                                BorderColor3 = Color3.new(0, 0, 0),
                                BorderSizePixel = 0,
                                Position = UDim2.new(0.355954975, 0, 0.500000179, 0),
                                Size = UDim2.new(0.585849345, 0, 1.01747024, 0),
                                Text = "Loading",
                                TextColor3 = Color3.new(1, 0.90196079, 0.431372553),
                                TextScaled = true,
                                TextSize = 20,
                                TextWrapped = true,
                                TextXAlignment = Enum.TextXAlignment.Right,
                                FontFace = Font.new("rbxasset://fonts/families/Montserrat.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
                                TextStrokeTransparency = 1,
                                TextYAlignment = Enum.TextYAlignment.Center
                            }
                        },
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UIAspectRatioConstraint",
                                    Name = "UIAspectRatioConstraint",
                                    Properties = {}
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UISizeConstraint",
                                    Name = "UISizeConstraint",
                                    Properties = {
                                        MaxSize = Vector2.new(30, 30),
                                        MinSize = Vector2.new(0, 0)
                                    }
                                }
                            },
                            ClassName = "ImageLabel",
                            Name = "ImageLabel",
                            Properties = {
                                AnchorPoint = Vector2.new(0.5, 0.5),
                                BackgroundTransparency = 1,
                                Image = "rbxassetid://11713337390",
                                ImageColor3 = Color3.new(0, 0, 0),
                                LayoutOrder = 2,
                                Position = UDim2.new(0.889260292, 0, 0.910417259, 0),
                                Size = UDim2.new(0.221479446, 0, 1.27280772, 0),
                                ImageTransparency = 0,
                                ScaleType = Enum.ScaleType.Stretch,
                                SizeConstraint = Enum.SizeConstraint.RelativeXY,
                                ZIndex = 1
                            }
                        },
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UIListLayout",
                            Name = "UIListLayout",
                            Properties = {
                                FillDirection = Enum.FillDirection.Horizontal,
                                HorizontalAlignment = Enum.HorizontalAlignment.Right,
                                Padding = UDim.new(0, 3),
                                SortOrder = Enum.SortOrder.LayoutOrder,
                                VerticalAlignment = Enum.VerticalAlignment.Center
                            }
                        },
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UICorner",
                            Name = "UICorner",
                            Properties = {}
                        }
                    },
                    ClassName = "Frame",
                    Name = "Gold",
                    Properties = {
                        AnchorPoint = Vector2.new(1, 0.5),
                        BackgroundColor3 = Color3.new(0, 0, 0),
                        BackgroundTransparency = 0.550000011920929,
                        BorderColor3 = Color3.new(0, 0, 0),
                        BorderSizePixel = 0,
                        Position = UDim2.new(0.97025913, 0, 0.206510812, 0),
                        Size = UDim2.new(0.93889159, 0, 0.0899721533, 0)
                    }
                },
                {
                    Attributes = {},
                    Children = {
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UICorner",
                            Name = "UICorner",
                            Properties = {
                                CornerRadius = UDim.new(0, 8)
                            }
                        },
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UITextSizeConstraint",
                            Name = "UITextSizeConstraint",
                            Properties = {
                                MinTextSize = 1,
                                MaxTextSize = 30
                            }
                        },
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UIAspectRatioConstraint",
                            Name = "UIAspectRatioConstraint",
                            Properties = {}
                        }
                    },
                    ClassName = "TextButton",
                    Name = "Level",
                    Properties = {
                        Active = false,
                        AnchorPoint = Vector2.new(1, 0),
                        BackgroundColor3 = Color3.fromRGB(51, 167, 255),
                        BorderColor3 = Color3.new(0, 0, 0),
                        BorderSizePixel = 0,
                        Position = UDim2.new(0.180129185, 0, 0.0311307311, 0),
                        Selectable = false,
                        Size = UDim2.new(0.160374627, 0, 0.111776322, 0),
                        Text = "32",
                        TextColor3 = Color3.new(1, 1, 1),
                        TextScaled = true,
                        TextWrapped = true,
                        BackgroundTransparency = 0,
                        SizeConstraint = Enum.SizeConstraint.RelativeXY,
                        ZIndex = 1,
                        Visible = true,
                        FontFace = Font.new("rbxasset://fonts/families/Montserrat.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
                        TextSize = 8,
                        TextStrokeColor3 = Color3.new(0, 0, 0),
                        TextStrokeTransparency = 1,
                        TextTransparency = 0,
                        TextXAlignment = Enum.TextXAlignment.Center,
                        TextYAlignment = Enum.TextYAlignment.Center,
                        LineHeight = 1
                    }
                },
                {
                    Attributes = {},
                    Children = {
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {
                                        CornerRadius = UDim.new(0, 8)
                                    }
                                },
                                {
                                    Attributes = {},
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {
                                                MinTextSize = 1,
                                                MaxTextSize = 25
                                            }
                                        }
                                    },
                                    ClassName = "TextLabel",
                                    Name = "Percent",
                                    Properties = {
                                        AnchorPoint = Vector2.new(0.5, 0.5),
                                        AutomaticSize = Enum.AutomaticSize.X,
                                        BackgroundColor3 = Color3.new(1, 1, 1),
                                        BackgroundTransparency = 1,
                                        BorderColor3 = Color3.new(0, 0, 0),
                                        BorderSizePixel = 0,
                                        Position = UDim2.new(0.5, 0, 0.5, 0),
                                        Size = UDim2.new(1, 0, 1, 0),
                                        Text = "23%",
                                        TextColor3 = Color3.new(1, 1, 1),
                                        TextScaled = true,
                                        TextSize = 13,
                                        TextWrapped = true,
                                        ZIndex = 2,
                                        SizeConstraint = Enum.SizeConstraint.RelativeXY,
                                        Visible = true,
                                        FontFace = Font.new("rbxasset://fonts/families/Montserrat.json", Enum.FontWeight.Medium, Enum.FontStyle.Normal),
                                        TextStrokeColor3 = Color3.new(0, 0, 0),
                                        TextStrokeTransparency = 1,
                                        TextTransparency = 0,
                                        TextXAlignment = Enum.TextXAlignment.Center,
                                        TextYAlignment = Enum.TextYAlignment.Center,
                                        LineHeight = 1
                                    }
                                }
                            },
                            ClassName = "Frame",
                            Name = "bar",
                            Properties = {
                                AnchorPoint = Vector2.new(0, 0.5),
                                BackgroundColor3 = Color3.fromRGB(51, 167, 255),
                                BorderColor3 = Color3.new(0, 0, 0),
                                BorderSizePixel = 0,
                                Position = UDim2.new(0, 0, 0.5, 0),
                                Size = UDim2.new(0.300000012, 0, 1, 0),
                                BackgroundTransparency = 0,
                                SizeConstraint = Enum.SizeConstraint.RelativeXY,
                                ZIndex = 1,
                                Visible = true
                            }
                        },
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UICorner",
                            Name = "UICorner",
                            Properties = {}
                        }
                    },
                    ClassName = "Frame",
                    Name = "Exp",
                    Properties = {
                        AnchorPoint = Vector2.new(1, 0),
                        BackgroundColor3 = Color3.new(0, 0, 0),
                        BackgroundTransparency = 0.550000011920929,
                        BorderColor3 = Color3.new(0, 0, 0),
                        BorderSizePixel = 0,
                        Position = UDim2.new(0.97025919, 0, 0.0451027863, 0),
                        Size = UDim2.new(0.765451729, 0, 0.0838322118, 0)
                    }
                },
                {
                    Attributes = {},
                    Children = {
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UICorner",
                            Name = "UICorner",
                            Properties = {}
                        },
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UITextSizeConstraint",
                            Name = "UITextSizeConstraint",
                            Properties = {}
                        }
                    },
                    ClassName = "TextLabel",
                    Name = "Menu",
                    Properties = {
                        AnchorPoint = Vector2.new(1, 0),
                        BackgroundColor3 = Color3.new(0.443137288, 0.443137288, 0.443137288),
                        BackgroundTransparency = 1,
                        BorderColor3 = Color3.new(0, 0, 0),
                        BorderSizePixel = 0,
                        Font = Enum.Font.Gotham,
                        Position = UDim2.new(0.97025913, 0, 0, 0),
                        Size = UDim2.new(0.76545167, 0, 0.0411107726, 0),
                        Text = "XP",
                        TextColor3 = Color3.new(1, 1, 1),
                        TextScaled = true,
                        TextWrapped = true
                    }
                },
                {
                    Attributes = {},
                    Children = {
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UICorner",
                            Name = "UICorner",
                            Properties = {
                                CornerRadius = UDim.new(0, 8)
                            }
                        },
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UITextSizeConstraint",
                            Name = "UITextSizeConstraint",
                            Properties = {
                                MinTextSize = 1,
                                MaxTextSize = 30
                            }
                        }
                    },
                    ClassName = "TextButton",
                    Name = "Shop",
                    Properties = {
                        Active = false,
                        AnchorPoint = Vector2.new(1, 0),
                        BackgroundColor3 = Color3.fromRGB(170, 85, 0),
                        BorderColor3 = Color3.new(0, 0, 0),
                        BorderSizePixel = 0,
                        Position = UDim2.new(0.970209956, 0, 0.279497147, 0),
                        Selectable = false,
                        Size = UDim2.new(0.294964045, 0, 0.0838323385, 0),
                        Text = "Shop",
                        TextColor3 = Color3.new(1, 1, 1),
                        TextScaled = true,
                        TextWrapped = true,
                        BackgroundTransparency = 0,
                        SizeConstraint = Enum.SizeConstraint.RelativeXY,
                        ZIndex = 1,
                        Visible = true,
                        FontFace = Font.new("rbxasset://fonts/families/Montserrat.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
                        TextSize = 8,
                        TextStrokeColor3 = Color3.new(0, 0, 0),
                        TextStrokeTransparency = 1,
                        TextTransparency = 0,
                        TextXAlignment = Enum.TextXAlignment.Center,
                        TextYAlignment = Enum.TextYAlignment.Center,
                        LineHeight = 1
                    }
                },
                {
                    Attributes = {},
                    Children = {
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UICorner",
                            Name = "UICorner",
                            Properties = {
                                CornerRadius = UDim.new(0, 8)
                            }
                        },
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UITextSizeConstraint",
                            Name = "UITextSizeConstraint",
                            Properties = {
                                MinTextSize = 1,
                                MaxTextSize = 30
                            }
                        },
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {}
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UITextSizeConstraint",
                                    Name = "UITextSizeConstraint",
                                    Properties = {}
                                }
                            },
                            ClassName = "TextLabel",
                            Name = "Menu",
                            Properties = {
                                AnchorPoint = Vector2.new(0.5, 0.5),
                                BackgroundColor3 = Color3.new(0, 0, 0),
                                BackgroundTransparency = 1,
                                BorderColor3 = Color3.new(0, 0, 0),
                                BorderSizePixel = 0,
                                LayoutOrder = 1,
                                Position = UDim2.new(0.5, 0, 1.27669168, 0),
                                Size = UDim2.new(1, 0, 0.553381741, 0),
                                Text = "",
                                TextColor3 = Color3.new(0.709803939, 0.709803939, 0.709803939),
                                TextScaled = true,
                                TextWrapped = true,
                                TextYAlignment = Enum.TextYAlignment.Top
                            }
                        }
                    },
                    ClassName = "TextButton",
                    Name = "Trade",
                    Properties = {
                        Active = true,
                        AnchorPoint = Vector2.new(1, 0),
                        AutoButtonColor = true,
                        BackgroundColor3 = Color3.fromRGB(51, 167, 255),
                        BorderColor3 = Color3.new(0, 0, 0),
                        BorderSizePixel = 0,
                        Position = UDim2.new(0.625010431, 0, 0.279497147, 0),
                        Selectable = true,
                        Size = UDim2.new(0.294964045, 0, 0.0838323385, 0),
                        Text = "Trade",
                        TextColor3 = Color3.new(1, 1, 1),
                        TextScaled = true,
                        TextStrokeTransparency = 1,
                        TextTransparency = 0,
                        TextWrapped = true,
                        BackgroundTransparency = 0,
                        SizeConstraint = Enum.SizeConstraint.RelativeXY,
                        ZIndex = 1,
                        Visible = true,
                        FontFace = Font.new("rbxasset://fonts/families/Montserrat.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
                        TextSize = 8,
                        TextStrokeColor3 = Color3.new(0, 0, 0),
                        TextXAlignment = Enum.TextXAlignment.Center,
                        TextYAlignment = Enum.TextYAlignment.Center,
                        LineHeight = 1
                    }
                }
            },
            ClassName = "Frame",
            Name = "Left",
            Properties = {
                AnchorPoint = Vector2.new(0, 0.5),
                BackgroundColor3 = Color3.new(0, 0, 0),
                BackgroundTransparency = 0.5,
                BorderColor3 = Color3.new(0, 0, 0),
                BorderSizePixel = 0,
                Position = UDim2.new(0, 0, 0.5, 0),
                Size = UDim2.new(0.308999985, 0, 1, 0)
            }
        },
        {
            Attributes = {},
            Children = {
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UICorner",
                    Name = "UICorner",
                    Properties = {}
                },
                {
                    Attributes = {},
                    Children = {
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UICorner",
                            Name = "UICorner",
                            Properties = {}
                        },
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {}
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UITextSizeConstraint",
                                    Name = "UITextSizeConstraint",
                                    Properties = {}
                                }
                            },
                            ClassName = "TextButton",
                            Name = "Mods",
                            Properties = {
                                Active = false,
                                AnchorPoint = Vector2.new(1, 0),
                                BackgroundColor3 = Color3.new(1, 0.333333343, 0),
                                BorderColor3 = Color3.new(0, 0, 0),
                                BorderSizePixel = 0,
                                Font = Enum.Font.Gotham,
                                LayoutOrder = 1,
                                Position = UDim2.new(0.323905945, 0, 0.0592095256, 0),
                                Selectable = false,
                                Size = UDim2.new(0.323905945, 0, 0.881581068, 0),
                                Text = "Mods",
                                TextColor3 = Color3.new(1, 1, 1),
                                TextScaled = true,
                                TextWrapped = true
                            }
                        },
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UIListLayout",
                            Name = "UIListLayout",
                            Properties = {
                                FillDirection = Enum.FillDirection.Horizontal,
                                Padding = UDim.new(0, 2),
                                SortOrder = Enum.SortOrder.LayoutOrder,
                                VerticalAlignment = Enum.VerticalAlignment.Center
                            }
                        },
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {}
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UITextSizeConstraint",
                                    Name = "UITextSizeConstraint",
                                    Properties = {}
                                }
                            },
                            ClassName = "TextButton",
                            Name = "Settings",
                            Properties = {
                                Active = false,
                                AnchorPoint = Vector2.new(1, 0),
                                BackgroundColor3 = Color3.new(0.443137258, 0.443137258, 0.443137258),
                                BorderColor3 = Color3.new(0, 0, 0),
                                BorderSizePixel = 0,
                                Font = Enum.Font.Gotham,
                                LayoutOrder = 3,
                                Position = UDim2.new(0.984542787, 0, 0.0592095256, 0),
                                Selectable = false,
                                Size = UDim2.new(0.323906004, 0, 0.881581068, 0),
                                Text = "Settings",
                                TextColor3 = Color3.new(1, 1, 1),
                                TextScaled = true,
                                TextWrapped = true
                            }
                        },
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {}
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UITextSizeConstraint",
                                    Name = "UITextSizeConstraint",
                                    Properties = {}
                                }
                            },
                            ClassName = "TextButton",
                            Name = "Hiscores",
                            Properties = {
                                Active = false,
                                AnchorPoint = Vector2.new(1, 0),
                                BackgroundColor3 = Color3.new(0.443137288, 0.443137288, 0.443137288),
                                BorderColor3 = Color3.new(0, 0, 0),
                                BorderSizePixel = 0,
                                Font = Enum.Font.Gotham,
                                LayoutOrder = 2,
                                Position = UDim2.new(0.654224515, 0, 0.0592095256, 0),
                                Selectable = false,
                                Size = UDim2.new(0.323905855, 0, 0.881581068, 0),
                                Text = "Hiscores",
                                TextColor3 = Color3.new(1, 1, 1),
                                TextScaled = true,
                                TextWrapped = true
                            }
                        },
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UIPadding",
                            Name = "UIPadding",
                            Properties = {
                                PaddingLeft = UDim.new(0, 4)
                            }
                        }
                    },
                    ClassName = "Frame",
                    Name = "Select",
                    Properties = {
                        AnchorPoint = Vector2.new(1, 0.5),
                        BackgroundColor3 = Color3.new(0, 0, 0),
                        BackgroundTransparency = 0.5,
                        BorderColor3 = Color3.new(0, 0, 0),
                        BorderSizePixel = 0,
                        Position = UDim2.new(0.997302055, 0, 0.0664635077, 0),
                        Size = UDim2.new(0.999999285, 0, 0.116958953, 0)
                    }
                },
                {
                    Attributes = {},
                    Children = {
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {}
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UIListLayout",
                                    Name = "UIListLayout",
                                    Properties = {
                                        Padding = UDim.new(0, 2),
                                        SortOrder = Enum.SortOrder.LayoutOrder
                                    }
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UIPadding",
                                    Name = "UIPadding",
                                    Properties = {
                                        PaddingBottom = UDim.new(0, 4),
                                        PaddingLeft = UDim.new(0, 4),
                                        PaddingRight = UDim.new(0, 4),
                                        PaddingTop = UDim.new(0, 4)
                                    }
                                },
                                {
                                    Attributes = {},
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UICorner",
                                            Name = "UICorner",
                                            Properties = {
                                                CornerRadius = UDim.new(0, 6)
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        },
                                        {
                                            Attributes = {},
                                            Children = {
                                                {
                                                    Attributes = {},
                                                    Children = {},
                                                    ClassName = "UICorner",
                                                    Name = "UICorner",
                                                    Properties = {}
                                                },
                                                {
                                                    Attributes = {},
                                                    Children = {},
                                                    ClassName = "UITextSizeConstraint",
                                                    Name = "UITextSizeConstraint",
                                                    Properties = {}
                                                },
                                                {
                                                    Attributes = {},
                                                    Children = {},
                                                    ClassName = "UITextSizeConstraint",
                                                    Name = "ModeMenuTextSizeConstraint",
                                                    Properties = {}
                                                }
                                            },
                                            ClassName = "TextLabel",
                                            Name = "ModName",
                                            Properties = {
                                                BackgroundColor3 = Color3.new(0.443137288, 0.443137288, 0.443137288),
                                                BackgroundTransparency = 1,
                                                BorderColor3 = Color3.new(0, 0, 0),
                                                BorderSizePixel = 0,
                                                Font = Enum.Font.GothamMedium,
                                                LayoutOrder = 1,
                                                Position = UDim2.new(0.0299999993, 0, 0, 0),
                                                Size = UDim2.new(0.620000005, 0, 1, 0),
                                                Text = "Classic",
                                                TextColor3 = Color3.new(1, 1, 1),
                                                TextSize = 26,
                                                TextTruncate = Enum.TextTruncate.AtEnd,
                                                TextXAlignment = Enum.TextXAlignment.Left,
                                                ZIndex = 2
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {
                                                {
                                                    Attributes = {},
                                                    Children = {},
                                                    ClassName = "UICorner",
                                                    Name = "UICorner",
                                                    Properties = {}
                                                },
                                                {
                                                    Attributes = {},
                                                    Children = {},
                                                    ClassName = "UITextSizeConstraint",
                                                    Name = "UITextSizeConstraint",
                                                    Properties = {}
                                                },
                                                {
                                                    Attributes = {},
                                                    Children = {},
                                                    ClassName = "UITextSizeConstraint",
                                                    Name = "ModeMenuTextSizeConstraint",
                                                    Properties = {}
                                                }
                                            },
                                            ClassName = "TextLabel",
                                            Name = "PlayersValue",
                                            Properties = {
                                                BackgroundColor3 = Color3.new(0.443137288, 0.443137288, 0.443137288),
                                                BackgroundTransparency = 1,
                                                BorderColor3 = Color3.new(0, 0, 0),
                                                BorderSizePixel = 0,
                                                Font = Enum.Font.GothamMedium,
                                                LayoutOrder = 1,
                                                Position = UDim2.new(0.720000029, 0, 0, 0),
                                                Size = UDim2.new(0.239999995, 0, 1, 0),
                                                Text = "0",
                                                TextColor3 = Color3.new(1, 1, 1),
                                                TextSize = 32,
                                                TextTruncate = Enum.TextTruncate.AtEnd,
                                                ZIndex = 2
                                            }
                                        }
                                    },
                                    ClassName = "Frame",
                                    Name = "Mod",
                                    Properties = {
                                        BackgroundColor3 = Color3.new(0.443137258, 0.443137258, 0.443137258),
                                        BorderColor3 = Color3.new(0, 0, 0),
                                        BorderSizePixel = 0,
                                        ClipsDescendants = true,
                                        LayoutOrder = 1,
                                        Size = UDim2.new(1, -8, 0, 46),
                                        Visible = false
                                    }
                                }
                            },
                            ClassName = "ScrollingFrame",
                            Name = "Modes",
                            Properties = {
                                AutomaticCanvasSize = Enum.AutomaticSize.Y,
                                BackgroundColor3 = Color3.new(0, 0, 0),
                                BackgroundTransparency = 1,
                                BorderColor3 = Color3.new(0, 0, 0),
                                BorderSizePixel = 0,
                                CanvasSize = UDim2.new(0, 0, 0, 0),
                                Position = UDim2.new(0.0399999991, 0, 0.224999994, 0),
                                ScrollBarThickness = 7,
                                ScrollingDirection = Enum.ScrollingDirection.Y,
                                Selectable = false,
                                Size = UDim2.new(0.920000017, 0, 0.74000001, 0)
                            }
                        },
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {}
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UITextSizeConstraint",
                                    Name = "UITextSizeConstraint",
                                    Properties = {}
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UITextSizeConstraint",
                                    Name = "ModeHeaderSize",
                                    Properties = {}
                                }
                            },
                            ClassName = "TextLabel",
                            Name = "title",
                            Properties = {
                                BackgroundColor3 = Color3.new(0.172549024, 0.172549024, 0.172549024),
                                BackgroundTransparency = 1,
                                BorderColor3 = Color3.new(0, 0, 0),
                                BorderSizePixel = 0,
                                Font = Enum.Font.GothamMedium,
                                LayoutOrder = 2,
                                Position = UDim2.new(0.720000029, 0, 0.0250000004, 0),
                                Size = UDim2.new(0.239999995, 0, 0.075000003, 0),
                                Text = "Players",
                                TextColor3 = Color3.new(1, 1, 1),
                                TextSize = 18,
                                TextTruncate = Enum.TextTruncate.AtEnd,
                                ZIndex = 3
                            }
                        },
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {}
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UITextSizeConstraint",
                                    Name = "UITextSizeConstraint",
                                    Properties = {}
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UITextSizeConstraint",
                                    Name = "ModeHeaderSize",
                                    Properties = {}
                                }
                            },
                            ClassName = "TextLabel",
                            Name = "Menu",
                            Properties = {
                                BackgroundColor3 = Color3.new(0.443137288, 0.443137288, 0.443137288),
                                BackgroundTransparency = 1,
                                BorderColor3 = Color3.new(0, 0, 0),
                                BorderSizePixel = 0,
                                Font = Enum.Font.GothamMedium,
                                LayoutOrder = 2,
                                Position = UDim2.new(0.0399999991, 0, 0.0250000004, 0),
                                Size = UDim2.new(0.519999981, 0, 0.075000003, 0),
                                Text = "Game Mode",
                                TextColor3 = Color3.new(1, 1, 1),
                                TextSize = 18,
                                TextTruncate = Enum.TextTruncate.AtEnd,
                                TextXAlignment = Enum.TextXAlignment.Left,
                                ZIndex = 3
                            }
                        },
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UITextSizeConstraint",
                                    Name = "ModeButtonSize",
                                    Properties = {}
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {
                                        CornerRadius = UDim.new(0, 6)
                                    }
                                }
                            },
                            ClassName = "TextButton",
                            Name = "OfficialModesButton",
                            Properties = {
                                BackgroundColor3 = Color3.new(0.345098048, 0.345098048, 0.345098048),
                                BorderSizePixel = 0,
                                Font = Enum.Font.GothamBold,
                                Position = UDim2.new(0.0399999991, 0, 0.129999995, 0),
                                Size = UDim2.new(0.270000011, 0, 0.075000003, 0),
                                Text = "Official",
                                TextColor3 = Color3.new(1, 1, 1),
                                TextSize = 18,
                                ZIndex = 120
                            }
                        },
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UITextSizeConstraint",
                                    Name = "ModeButtonSize",
                                    Properties = {}
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {
                                        CornerRadius = UDim.new(0, 6)
                                    }
                                }
                            },
                            ClassName = "TextButton",
                            Name = "CustomModesButton",
                            Properties = {
                                BackgroundColor3 = Color3.new(0.345098048, 0.345098048, 0.345098048),
                                BorderSizePixel = 0,
                                Font = Enum.Font.GothamBold,
                                Position = UDim2.new(0.335000008, 0, 0.129999995, 0),
                                Size = UDim2.new(0.270000011, 0, 0.075000003, 0),
                                Text = "Custom",
                                TextColor3 = Color3.new(1, 1, 1),
                                TextSize = 18,
                                ZIndex = 120
                            }
                        },
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UITextSizeConstraint",
                                    Name = "ModeButtonSize",
                                    Properties = {}
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {
                                        CornerRadius = UDim.new(0, 6)
                                    }
                                }
                            },
                            ClassName = "TextButton",
                            Name = "CreateCustomModeButton",
                            Properties = {
                                BackgroundColor3 = Color3.new(1, 0.333333343, 0),
                                BorderSizePixel = 0,
                                Font = Enum.Font.GothamBold,
                                Position = UDim2.new(0.689999998, 0, 0.129999995, 0),
                                Size = UDim2.new(0.270000011, 0, 0.075000003, 0),
                                Text = "Create",
                                TextColor3 = Color3.new(1, 1, 1),
                                TextSize = 18,
                                Visible = false,
                                ZIndex = 120
                            }
                        },
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UITextSizeConstraint",
                                    Name = "ModeSearchSize",
                                    Properties = {}
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {
                                        CornerRadius = UDim.new(0, 6)
                                    }
                                }
                            },
                            ClassName = "TextBox",
                            Name = "CustomModeSearchBox",
                            Properties = {
                                BackgroundColor3 = Color3.new(0.282352954, 0.282352954, 0.282352954),
                                BorderSizePixel = 0,
                                ClearTextOnFocus = false,
                                Font = Enum.Font.GothamMedium,
                                PlaceholderColor3 = Color3.new(0.725490212, 0.725490212, 0.725490212),
                                PlaceholderText = "Search by mode name / owner / owner id",
                                Position = UDim2.new(0.0399999991, 0, 0.219999999, 0),
                                Size = UDim2.new(0.920000017, 0, 0.075000003, 0),
                                Text = "",
                                TextColor3 = Color3.new(1, 1, 1),
                                TextSize = 16,
                                TextTruncate = Enum.TextTruncate.AtEnd,
                                Visible = false,
                                ZIndex = 120
                            }
                        },
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {}
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UIListLayout",
                                    Name = "UIListLayout",
                                    Properties = {
                                        Padding = UDim.new(0, 2),
                                        SortOrder = Enum.SortOrder.LayoutOrder
                                    }
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UIPadding",
                                    Name = "UIPadding",
                                    Properties = {
                                        PaddingBottom = UDim.new(0, 4),
                                        PaddingLeft = UDim.new(0, 4),
                                        PaddingRight = UDim.new(0, 4),
                                        PaddingTop = UDim.new(0, 4)
                                    }
                                },
                                {
                                    Attributes = {},
                                    Children = {
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UICorner",
                                            Name = "UICorner",
                                            Properties = {
                                                CornerRadius = UDim.new(0, 6)
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {},
                                            ClassName = "UITextSizeConstraint",
                                            Name = "UITextSizeConstraint",
                                            Properties = {}
                                        },
                                        {
                                            Attributes = {},
                                            Children = {
                                                {
                                                    Attributes = {},
                                                    Children = {},
                                                    ClassName = "UICorner",
                                                    Name = "UICorner",
                                                    Properties = {}
                                                },
                                                {
                                                    Attributes = {},
                                                    Children = {},
                                                    ClassName = "UITextSizeConstraint",
                                                    Name = "UITextSizeConstraint",
                                                    Properties = {}
                                                },
                                                {
                                                    Attributes = {},
                                                    Children = {},
                                                    ClassName = "UITextSizeConstraint",
                                                    Name = "ModeMenuTextSizeConstraint",
                                                    Properties = {}
                                                }
                                            },
                                            ClassName = "TextLabel",
                                            Name = "ModName",
                                            Properties = {
                                                BackgroundColor3 = Color3.new(0.443137288, 0.443137288, 0.443137288),
                                                BackgroundTransparency = 1,
                                                BorderColor3 = Color3.new(0, 0, 0),
                                                BorderSizePixel = 0,
                                                Font = Enum.Font.GothamMedium,
                                                LayoutOrder = 1,
                                                Position = UDim2.new(0.0299999993, 0, 0, 0),
                                                Size = UDim2.new(0.620000005, 0, 1, 0),
                                                Text = "Classic",
                                                TextColor3 = Color3.new(1, 1, 1),
                                                TextSize = 26,
                                                TextTruncate = Enum.TextTruncate.AtEnd,
                                                TextXAlignment = Enum.TextXAlignment.Left,
                                                ZIndex = 2
                                            }
                                        },
                                        {
                                            Attributes = {},
                                            Children = {
                                                {
                                                    Attributes = {},
                                                    Children = {},
                                                    ClassName = "UICorner",
                                                    Name = "UICorner",
                                                    Properties = {}
                                                },
                                                {
                                                    Attributes = {},
                                                    Children = {},
                                                    ClassName = "UITextSizeConstraint",
                                                    Name = "UITextSizeConstraint",
                                                    Properties = {}
                                                },
                                                {
                                                    Attributes = {},
                                                    Children = {},
                                                    ClassName = "UITextSizeConstraint",
                                                    Name = "ModeMenuTextSizeConstraint",
                                                    Properties = {}
                                                }
                                            },
                                            ClassName = "TextLabel",
                                            Name = "PlayersValue",
                                            Properties = {
                                                BackgroundColor3 = Color3.new(0.443137288, 0.443137288, 0.443137288),
                                                BackgroundTransparency = 1,
                                                BorderColor3 = Color3.new(0, 0, 0),
                                                BorderSizePixel = 0,
                                                Font = Enum.Font.GothamMedium,
                                                LayoutOrder = 1,
                                                Position = UDim2.new(0.720000029, 0, 0, 0),
                                                Size = UDim2.new(0.239999995, 0, 1, 0),
                                                Text = "0",
                                                TextColor3 = Color3.new(1, 1, 1),
                                                TextSize = 32,
                                                TextTruncate = Enum.TextTruncate.AtEnd,
                                                ZIndex = 2
                                            }
                                        }
                                    },
                                    ClassName = "Frame",
                                    Name = "Mod",
                                    Properties = {
                                        BackgroundColor3 = Color3.new(0.443137258, 0.443137258, 0.443137258),
                                        BorderColor3 = Color3.new(0, 0, 0),
                                        BorderSizePixel = 0,
                                        ClipsDescendants = true,
                                        LayoutOrder = 1,
                                        Size = UDim2.new(1, -8, 0, 46),
                                        Visible = false
                                    }
                                }
                            },
                            ClassName = "ScrollingFrame",
                            Name = "CustomModes",
                            Properties = {
                                AutomaticCanvasSize = Enum.AutomaticSize.Y,
                                BackgroundColor3 = Color3.new(0, 0, 0),
                                BackgroundTransparency = 1,
                                BorderColor3 = Color3.new(0, 0, 0),
                                BorderSizePixel = 0,
                                CanvasSize = UDim2.new(0, 0, 0, 0),
                                Position = UDim2.new(0.0399999991, 0, 0.310000002, 0),
                                ScrollBarThickness = 7,
                                ScrollingDirection = Enum.ScrollingDirection.Y,
                                Selectable = false,
                                Size = UDim2.new(0.920000017, 0, 0.654999971, 0),
                                Visible = false
                            }
                        }
                    },
                    ClassName = "Frame",
                    Name = "Mods",
                    Properties = {
                        AnchorPoint = Vector2.new(1, 0.5),
                        BackgroundColor3 = Color3.new(0, 0, 0),
                        BackgroundTransparency = 0.5,
                        BorderColor3 = Color3.new(0, 0, 0),
                        BorderSizePixel = 0,
                        Position = UDim2.new(0.999998987, 0, 0.56446749, 0),
                        Size = UDim2.new(0.999999285, 0, 0.871065021, 0)
                    }
                }
            },
            ClassName = "Frame",
            Name = "Right",
            Properties = {
                AnchorPoint = Vector2.new(1, 0.5),
                BackgroundColor3 = Color3.new(0, 0, 0),
                BackgroundTransparency = 0.5,
                BorderColor3 = Color3.new(0, 0, 0),
                BorderSizePixel = 0,
                Position = UDim2.new(1, 0, 0.5, 0),
                Size = UDim2.new(0.308999985, 0, 1, 0)
            }
        }
    },
    ClassName = "Frame",
    Name = "Menu",
    Properties = {
        AnchorPoint = Vector2.new(0.5, 0.5),
        BackgroundColor3 = Color3.new(1, 1, 1),
        BackgroundTransparency = 1,
        BorderColor3 = Color3.new(0, 0, 0),
        BorderSizePixel = 0,
        Position = UDim2.new(0.5, 0, 0.5, 28),
        Size = UDim2.new(0.899999976, 0, 0.899999976, 0)
    }
};