-- ClassName: ModuleScript
-- Roblox Path: game.ReplicatedStorage.Framework.GeneratedUI.GuiSpecParts.Gui_Shop_Title_17

-- Decompiled with Potassium's decompiler.

return {
    Attributes = {},
    Children = {
        {
            Attributes = {},
            Children = {},
            ClassName = "UICorner",
            Name = "UICorner",
            Properties = {}
        }
    },
    ClassName = "TextLabel",
    Name = "Title",
    Properties = {
        AnchorPoint = Vector2.new(1, 0),
        BackgroundColor3 = Color3.new(0.172549024, 0.172549024, 0.172549024),
        BackgroundTransparency = 1,
        BorderColor3 = Color3.new(0, 0, 0),
        BorderSizePixel = 0,
        Font = Enum.Font.GothamBold,
        LayoutOrder = 2,
        Position = UDim2.new(1.00055265, 0, 1.00145113, 0),
        Size = UDim2.new(1.00024676, 0, 0.0522161722, 0),
        Text = "The game is new. Creation date: April 10, 2026.",
        TextColor3 = Color3.new(0.203921586, 0.203921586, 0.203921586),
        TextScaled = true,
        TextWrapped = true
    }
};