-- ClassName: ModuleScript
-- Roblox Path: game.ReplicatedStorage.Framework.GeneratedUI.GuiSpecParts.Gui_Abilities_24

-- Decompiled with Potassium's decompiler.

return {
    Attributes = {},
    Children = {
        {
            Attributes = {},
            Children = {},
            ClassName = "UIListLayout",
            Name = "UIListLayout",
            Properties = {
                HorizontalAlignment = Enum.HorizontalAlignment.Center,
                Padding = UDim.new(0.00499999989, 0),
                SortOrder = Enum.SortOrder.LayoutOrder,
                VerticalAlignment = Enum.VerticalAlignment.Bottom
            }
        },
        {
            Attributes = {},
            Children = {
                {
                    Attributes = {},
                    Children = {
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UIAspectRatioConstraint",
                            Name = "UIAspectRatioConstraint",
                            Properties = {}
                        },
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UICorner",
                            Name = "UICorner",
                            Properties = {}
                        },
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "TextLabel",
                            Name = "Amount",
                            Properties = {
                                BackgroundColor3 = Color3.new(1, 1, 1),
                                BackgroundTransparency = 1,
                                BorderColor3 = Color3.new(0, 0, 0),
                                BorderSizePixel = 0,
                                Font = Enum.Font.Unknown,
                                Position = UDim2.new(0.0764613822, 0, 0.474671215, 0),
                                RichText = true,
                                Size = UDim2.new(0.835043728, 0, 0.547454894, 0),
                                Text = "2",
                                TextColor3 = Color3.new(1, 1, 1),
                                TextScaled = true,
                                TextSize = 14,
                                TextStrokeTransparency = 0.5,
                                TextWrapped = true,
                                TextXAlignment = Enum.TextXAlignment.Right
                            }
                        }
                    },
                    ClassName = "ImageButton",
                    Name = "TemplateButton",
                    Properties = {
                        AnchorPoint = Vector2.new(0.5, 0.5),
                        BackgroundColor3 = Color3.new(0, 0, 0),
                        BackgroundTransparency = 0.44999998807907104,
                        BorderColor3 = Color3.new(0, 0, 0),
                        BorderSizePixel = 0,
                        LayoutOrder = 1,
                        Position = UDim2.new(0.500248671, 0, 0.509209573, 0),
                        Size = UDim2.new(0.200000003, 0, 1, 0),
                        Visible = false
                    }
                },
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UIListLayout",
                    Name = "UIListLayout",
                    Properties = {
                        FillDirection = Enum.FillDirection.Horizontal,
                        HorizontalAlignment = Enum.HorizontalAlignment.Center,
                        Padding = UDim.new(0.00499999989, 0),
                        SortOrder = Enum.SortOrder.LayoutOrder,
                        VerticalAlignment = Enum.VerticalAlignment.Bottom
                    }
                },
                {
                    Attributes = {},
                    Children = {
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UIAspectRatioConstraint",
                            Name = "UIAspectRatioConstraint",
                            Properties = {}
                        },
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UICorner",
                            Name = "UICorner",
                            Properties = {}
                        },
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "TextLabel",
                            Name = "Amount",
                            Properties = {
                                AnchorPoint = Vector2.new(0.5, 0.5),
                                BackgroundColor3 = Color3.new(1, 1, 1),
                                BackgroundTransparency = 1,
                                BorderColor3 = Color3.new(0, 0, 0),
                                BorderSizePixel = 0,
                                Font = Enum.Font.Unknown,
                                Position = UDim2.new(0.539682269, 0, 0.380952418, 0),
                                RichText = true,
                                Rotation = 90,
                                Size = UDim2.new(0.761904299, 0, 0.920634925, 0),
                                Text = ">",
                                TextColor3 = Color3.new(1, 1, 1),
                                TextScaled = true,
                                TextSize = 14,
                                TextStrokeTransparency = 0.5,
                                TextWrapped = true,
                                TextXAlignment = Enum.TextXAlignment.Right
                            }
                        }
                    },
                    ClassName = "ImageButton",
                    Name = "Close",
                    Properties = {
                        AnchorPoint = Vector2.new(0.5, 0.5),
                        BackgroundColor3 = Color3.new(0, 0, 0),
                        BackgroundTransparency = 0.44999998807907104,
                        BorderColor3 = Color3.new(0, 0, 0),
                        BorderSizePixel = 0,
                        LayoutOrder = 10000,
                        Position = UDim2.new(0.557700038, 0, 0.721238971, 0),
                        Size = UDim2.new(0.0703999773, 0, 0.557522237, 0),
                        Visible = false
                    }
                }
            },
            ClassName = "Frame",
            Name = "Bottom1ScreenGui",
            Properties = {
                AnchorPoint = Vector2.new(0.5, 0.5),
                BackgroundColor3 = Color3.new(1, 1, 1),
                BackgroundTransparency = 1,
                BorderColor3 = Color3.new(0, 0, 0),
                BorderSizePixel = 0,
                LayoutOrder = 2,
                Position = UDim2.new(0.5, 0, 0.828687072, -3),
                Size = UDim2.new(1, 0, 0.112999998, 0)
            }
        },
        {
            Attributes = {},
            Children = {},
            ClassName = "UISizeConstraint",
            Name = "UISizeConstraint",
            Properties = {
                MaxSize = Vector2.new(500, 400)
            }
        }
    },
    ClassName = "Frame",
    Name = "Abilities",
    Properties = {
        AnchorPoint = Vector2.new(0.5, 1),
        BackgroundColor3 = Color3.new(1, 1, 1),
        BackgroundTransparency = 1,
        BorderColor3 = Color3.new(0, 0, 0),
        BorderSizePixel = 0,
        Position = UDim2.new(0.5, 0, 1, -2),
        Size = UDim2.new(1, 0, 0.999999583, 0),
        ZIndex = 100
    }
};