-- ClassName: ModuleScript
-- Roblox Path: game.ReplicatedStorage.Framework.GeneratedUI.GuiSpecParts.Gui_Shop_Avatar_19

-- Decompiled with Potassium's decompiler.

return {
    Attributes = {},
    Children = {
        {
            Attributes = {},
            Children = {},
            ClassName = "UICorner",
            Name = "UICorner",
            Properties = {
                CornerRadius = UDim.new(1, 0)
            }
        },
        {
            Attributes = {},
            Children = {},
            ClassName = "UITextSizeConstraint",
            Name = "UITextSizeConstraint",
            Properties = {}
        },
        {
            Attributes = {},
            Children = {},
            ClassName = "UIAspectRatioConstraint",
            Name = "UIAspectRatioConstraint",
            Properties = {}
        }
    },
    ClassName = "ImageButton",
    Name = "Avatar",
    Properties = {
        Active = false,
        AnchorPoint = Vector2.new(0.5, 0),
        AutoButtonColor = false,
        BackgroundColor3 = Color3.new(0.443137288, 0.443137288, 0.443137288),
        BorderColor3 = Color3.new(0, 0, 0),
        BorderSizePixel = 0,
        LayoutOrder = 1,
        Position = UDim2.new(0.899557829, 0, 0.45439738, 0),
        Selectable = false,
        Size = UDim2.new(0.203808144, 0, 0.344496548, 0),
        ZIndex = 10
    }
};