-- ClassName: ModuleScript
-- Roblox Path: game.ReplicatedStorage.Framework.GeneratedUI.GuiSpecParts.Gui_ActiveTradeSession_23

-- Decompiled with Potassium's decompiler.

return {
    Attributes = {},
    Children = {
        {
            Attributes = {},
            Children = {},
            ClassName = "UIAspectRatioConstraint",
            Name = "UIAspectRatioConstraint",
            Properties = {
                AspectRatio = 2
            }
        },
        {
            Attributes = {},
            Children = {
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UICorner",
                    Name = "UICorner",
                    Properties = {}
                },
                {
                    Attributes = {},
                    Children = {
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UICorner",
                            Name = "UICorner",
                            Properties = {}
                        }
                    },
                    ClassName = "TextButton",
                    Name = "Decline",
                    Properties = {
                        AnchorPoint = Vector2.new(0.5, 0.5),
                        AutoButtonColor = false,
                        BackgroundColor3 = Color3.new(0.784313738, 0.235294119, 0.235294119),
                        BorderColor3 = Color3.new(0, 0, 0),
                        BorderSizePixel = 0,
                        Font = Enum.Font.SourceSans,
                        Position = UDim2.new(0.800000012, 0, 0.5, 0),
                        Size = UDim2.new(0.100000001, 0, 0.5, 10),
                        Text = "Decline",
                        TextColor3 = Color3.new(1, 1, 1),
                        TextScaled = true,
                        TextSize = 14,
                        TextWrapped = true
                    }
                },
                {
                    Attributes = {},
                    Children = {
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UICorner",
                            Name = "UICorner",
                            Properties = {}
                        }
                    },
                    ClassName = "TextButton",
                    Name = "Accept",
                    Properties = {
                        AnchorPoint = Vector2.new(0.5, 0.5),
                        AutoButtonColor = false,
                        BackgroundColor3 = Color3.new(0.274509817, 0.70588237, 0.274509817),
                        BorderColor3 = Color3.new(0, 0, 0),
                        BorderSizePixel = 0,
                        Font = Enum.Font.SourceSans,
                        Position = UDim2.new(0.939999998, 0, 0.5, 0),
                        Size = UDim2.new(0.100000001, 0, 0.5, 10),
                        Text = "Accept",
                        TextColor3 = Color3.new(1, 1, 1),
                        TextScaled = true,
                        TextSize = 14,
                        TextWrapped = true
                    }
                },
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "TextLabel",
                    Name = "TextLabel",
                    Properties = {
                        AnchorPoint = Vector2.new(0.5, 0.5),
                        BackgroundColor3 = Color3.new(0.701960802, 0.701960802, 0.701960802),
                        BackgroundTransparency = 1,
                        BorderColor3 = Color3.new(0, 0, 0),
                        BorderSizePixel = 0,
                        Font = Enum.Font.Unknown,
                        Position = UDim2.new(0.370000005, 0, 0.5, 0),
                        Size = UDim2.new(0.699999988, 0, 0.5, 10),
                        Text = "Trade with Player1",
                        TextColor3 = Color3.new(1, 1, 1),
                        TextSize = 20,
                        TextStrokeTransparency = 0.8999999761581421,
                        TextXAlignment = Enum.TextXAlignment.Left
                    }
                }
            },
            ClassName = "Frame",
            Name = "Buttons",
            Properties = {
                AnchorPoint = Vector2.new(0.5, 0.5),
                BackgroundColor3 = Color3.new(0.701960802, 0.701960802, 0.701960802),
                BackgroundTransparency = 0.5,
                BorderColor3 = Color3.new(0, 0, 0),
                BorderSizePixel = 0,
                Position = UDim2.new(0.5, 0, 0.930000007, 0),
                Size = UDim2.new(1, 0, 0.136999995, 0)
            }
        },
        {
            Attributes = {},
            Children = {
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UICorner",
                    Name = "UICorner",
                    Properties = {}
                },
                {
                    Attributes = {},
                    Children = {
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UICorner",
                            Name = "UICorner",
                            Properties = {}
                        }
                    },
                    ClassName = "TextLabel",
                    Name = "TextLabel",
                    Properties = {
                        BackgroundColor3 = Color3.new(0.701960802, 0.701960802, 0.701960802),
                        BackgroundTransparency = 0.5,
                        BorderColor3 = Color3.new(0, 0, 0),
                        BorderSizePixel = 0,
                        Font = Enum.Font.Unknown,
                        Size = UDim2.new(1, 0, 0.25, 0),
                        Text = " Player1",
                        TextColor3 = Color3.new(1, 1, 1),
                        TextSize = 20,
                        TextStrokeTransparency = 0.8999999761581421,
                        TextXAlignment = Enum.TextXAlignment.Left
                    }
                },
                {
                    Attributes = {},
                    Children = {
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UIListLayout",
                            Name = "UIListLayout",
                            Properties = {
                                FillDirection = Enum.FillDirection.Horizontal,
                                Padding = UDim.new(0, 6),
                                SortOrder = Enum.SortOrder.LayoutOrder
                            }
                        },
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {}
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "TextLabel",
                                    Name = "TextLabel",
                                    Properties = {
                                        AnchorPoint = Vector2.new(0.5, 0.5),
                                        BackgroundColor3 = Color3.new(1, 1, 1),
                                        BackgroundTransparency = 1,
                                        BorderColor3 = Color3.new(0, 0, 0),
                                        BorderSizePixel = 0,
                                        Font = Enum.Font.SourceSans,
                                        Position = UDim2.new(0.5, 0, 0.5, 0),
                                        Size = UDim2.new(1, 0, 1, 0),
                                        Text = "+",
                                        TextColor3 = Color3.new(1, 1, 1),
                                        TextScaled = true,
                                        TextSize = 14,
                                        TextWrapped = true
                                    }
                                }
                            },
                            ClassName = "TextButton",
                            Name = "AddButton",
                            Properties = {
                                AutoButtonColor = false,
                                BackgroundColor3 = Color3.new(0, 0, 0),
                                BackgroundTransparency = 0.5,
                                BorderColor3 = Color3.new(0, 0, 0),
                                BorderSizePixel = 0,
                                Font = Enum.Font.SourceSans,
                                Size = UDim2.new(0.118000001, 0, 1, 0),
                                Text = "",
                                TextColor3 = Color3.new(0, 0, 0),
                                TextSize = 14
                            }
                        },
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {}
                                }
                            },
                            ClassName = "TextButton",
                            Name = "EmptySlot",
                            Properties = {
                                AutoButtonColor = false,
                                BackgroundColor3 = Color3.new(0.835294187, 0.835294187, 0.835294187),
                                BackgroundTransparency = 0.5,
                                BorderColor3 = Color3.new(0, 0, 0),
                                BorderSizePixel = 0,
                                Font = Enum.Font.SourceSans,
                                Position = UDim2.new(0.1258993, 0, 0, 0),
                                Size = UDim2.new(0.118000001, 0, 1, 0),
                                Text = "",
                                TextColor3 = Color3.new(0, 0, 0),
                                TextSize = 14
                            }
                        },
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {}
                                }
                            },
                            ClassName = "TextButton",
                            Name = "EmptySlot",
                            Properties = {
                                AutoButtonColor = false,
                                BackgroundColor3 = Color3.new(0.835294187, 0.835294187, 0.835294187),
                                BackgroundTransparency = 0.5,
                                BorderColor3 = Color3.new(0, 0, 0),
                                BorderSizePixel = 0,
                                Font = Enum.Font.SourceSans,
                                Position = UDim2.new(0.1258993, 0, 0, 0),
                                Size = UDim2.new(0.118000001, 0, 1, 0),
                                Text = "",
                                TextColor3 = Color3.new(0, 0, 0),
                                TextSize = 14
                            }
                        },
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {}
                                }
                            },
                            ClassName = "TextButton",
                            Name = "EmptySlot",
                            Properties = {
                                AutoButtonColor = false,
                                BackgroundColor3 = Color3.new(0.835294187, 0.835294187, 0.835294187),
                                BackgroundTransparency = 0.5,
                                BorderColor3 = Color3.new(0, 0, 0),
                                BorderSizePixel = 0,
                                Font = Enum.Font.SourceSans,
                                Position = UDim2.new(0.1258993, 0, 0, 0),
                                Size = UDim2.new(0.118000001, 0, 1, 0),
                                Text = "",
                                TextColor3 = Color3.new(0, 0, 0),
                                TextSize = 14
                            }
                        },
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {}
                                }
                            },
                            ClassName = "TextButton",
                            Name = "EmptySlot",
                            Properties = {
                                AutoButtonColor = false,
                                BackgroundColor3 = Color3.new(0.835294187, 0.835294187, 0.835294187),
                                BackgroundTransparency = 0.5,
                                BorderColor3 = Color3.new(0, 0, 0),
                                BorderSizePixel = 0,
                                Font = Enum.Font.SourceSans,
                                Position = UDim2.new(0.1258993, 0, 0, 0),
                                Size = UDim2.new(0.118000001, 0, 1, 0),
                                Text = "",
                                TextColor3 = Color3.new(0, 0, 0),
                                TextSize = 14
                            }
                        },
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {}
                                }
                            },
                            ClassName = "TextButton",
                            Name = "EmptySlot",
                            Properties = {
                                AutoButtonColor = false,
                                BackgroundColor3 = Color3.new(0.835294187, 0.835294187, 0.835294187),
                                BackgroundTransparency = 0.5,
                                BorderColor3 = Color3.new(0, 0, 0),
                                BorderSizePixel = 0,
                                Font = Enum.Font.SourceSans,
                                Position = UDim2.new(0.1258993, 0, 0, 0),
                                Size = UDim2.new(0.118000001, 0, 1, 0),
                                Text = "",
                                TextColor3 = Color3.new(0, 0, 0),
                                TextSize = 14
                            }
                        },
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {}
                                }
                            },
                            ClassName = "TextButton",
                            Name = "EmptySlot",
                            Properties = {
                                AutoButtonColor = false,
                                BackgroundColor3 = Color3.new(0.835294187, 0.835294187, 0.835294187),
                                BackgroundTransparency = 0.5,
                                BorderColor3 = Color3.new(0, 0, 0),
                                BorderSizePixel = 0,
                                Font = Enum.Font.SourceSans,
                                Position = UDim2.new(0.1258993, 0, 0, 0),
                                Size = UDim2.new(0.118000001, 0, 1, 0),
                                Text = "",
                                TextColor3 = Color3.new(0, 0, 0),
                                TextSize = 14
                            }
                        },
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {}
                                }
                            },
                            ClassName = "TextButton",
                            Name = "EmptySlot",
                            Properties = {
                                AutoButtonColor = false,
                                BackgroundColor3 = Color3.new(0.835294187, 0.835294187, 0.835294187),
                                BackgroundTransparency = 0.5,
                                BorderColor3 = Color3.new(0, 0, 0),
                                BorderSizePixel = 0,
                                Font = Enum.Font.SourceSans,
                                Position = UDim2.new(0.1258993, 0, 0, 0),
                                Size = UDim2.new(0.118000001, 0, 1, 0),
                                Text = "",
                                TextColor3 = Color3.new(0, 0, 0),
                                TextSize = 14
                            }
                        }
                    },
                    ClassName = "ScrollingFrame",
                    Name = "ScrollingFrame",
                    Properties = {
                        BackgroundColor3 = Color3.new(1, 1, 1),
                        BackgroundTransparency = 1,
                        BorderColor3 = Color3.new(0, 0, 0),
                        BorderSizePixel = 0,
                        CanvasSize = UDim2.new(0, 0, 0, 0),
                        Position = UDim2.new(0.0109999999, 0, 0.268000007, 0),
                        ScrollBarImageColor3 = Color3.new(0, 0, 0),
                        Size = UDim2.new(0.97299999, 0, 0.686999977, 0)
                    }
                }
            },
            ClassName = "Frame",
            Name = "Your",
            Properties = {
                AnchorPoint = Vector2.new(0.5, 0.5),
                BackgroundColor3 = Color3.new(0, 0, 0),
                BackgroundTransparency = 0.699999988079071,
                BorderColor3 = Color3.new(0, 0, 0),
                BorderSizePixel = 0,
                Position = UDim2.new(0.5, 0, 0.193000004, 0),
                Size = UDim2.new(1, 0, 0.389999986, 0)
            }
        },
        {
            Attributes = {},
            Children = {
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UICorner",
                    Name = "UICorner",
                    Properties = {}
                },
                {
                    Attributes = {},
                    Children = {
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UICorner",
                            Name = "UICorner",
                            Properties = {}
                        }
                    },
                    ClassName = "TextLabel",
                    Name = "TextLabel",
                    Properties = {
                        BackgroundColor3 = Color3.new(0.701960802, 0.701960802, 0.701960802),
                        BackgroundTransparency = 0.5,
                        BorderColor3 = Color3.new(0, 0, 0),
                        BorderSizePixel = 0,
                        Font = Enum.Font.Unknown,
                        Size = UDim2.new(1, 0, 0.25, 0),
                        Text = " Player1",
                        TextColor3 = Color3.new(1, 1, 1),
                        TextSize = 20,
                        TextStrokeTransparency = 0.8999999761581421,
                        TextXAlignment = Enum.TextXAlignment.Left
                    }
                },
                {
                    Attributes = {},
                    Children = {
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UIListLayout",
                            Name = "UIListLayout",
                            Properties = {
                                FillDirection = Enum.FillDirection.Horizontal,
                                Padding = UDim.new(0, 6),
                                SortOrder = Enum.SortOrder.LayoutOrder
                            }
                        },
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {}
                                }
                            },
                            ClassName = "TextButton",
                            Name = "EmptySlot",
                            Properties = {
                                AutoButtonColor = false,
                                BackgroundColor3 = Color3.new(0.835294187, 0.835294187, 0.835294187),
                                BackgroundTransparency = 0.5,
                                BorderColor3 = Color3.new(0, 0, 0),
                                BorderSizePixel = 0,
                                Font = Enum.Font.SourceSans,
                                Position = UDim2.new(0.1258993, 0, 0, 0),
                                Size = UDim2.new(0.118000001, 0, 1, 0),
                                Text = "",
                                TextColor3 = Color3.new(0, 0, 0),
                                TextSize = 14
                            }
                        },
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {}
                                }
                            },
                            ClassName = "TextButton",
                            Name = "EmptySlot",
                            Properties = {
                                AutoButtonColor = false,
                                BackgroundColor3 = Color3.new(0.835294187, 0.835294187, 0.835294187),
                                BackgroundTransparency = 0.5,
                                BorderColor3 = Color3.new(0, 0, 0),
                                BorderSizePixel = 0,
                                Font = Enum.Font.SourceSans,
                                Position = UDim2.new(0.1258993, 0, 0, 0),
                                Size = UDim2.new(0.118000001, 0, 1, 0),
                                Text = "",
                                TextColor3 = Color3.new(0, 0, 0),
                                TextSize = 14
                            }
                        },
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {}
                                }
                            },
                            ClassName = "TextButton",
                            Name = "EmptySlot",
                            Properties = {
                                AutoButtonColor = false,
                                BackgroundColor3 = Color3.new(0.835294187, 0.835294187, 0.835294187),
                                BackgroundTransparency = 0.5,
                                BorderColor3 = Color3.new(0, 0, 0),
                                BorderSizePixel = 0,
                                Font = Enum.Font.SourceSans,
                                Position = UDim2.new(0.1258993, 0, 0, 0),
                                Size = UDim2.new(0.118000001, 0, 1, 0),
                                Text = "",
                                TextColor3 = Color3.new(0, 0, 0),
                                TextSize = 14
                            }
                        },
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {}
                                }
                            },
                            ClassName = "TextButton",
                            Name = "EmptySlot",
                            Properties = {
                                AutoButtonColor = false,
                                BackgroundColor3 = Color3.new(0.835294187, 0.835294187, 0.835294187),
                                BackgroundTransparency = 0.5,
                                BorderColor3 = Color3.new(0, 0, 0),
                                BorderSizePixel = 0,
                                Font = Enum.Font.SourceSans,
                                Position = UDim2.new(0.1258993, 0, 0, 0),
                                Size = UDim2.new(0.118000001, 0, 1, 0),
                                Text = "",
                                TextColor3 = Color3.new(0, 0, 0),
                                TextSize = 14
                            }
                        },
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {}
                                }
                            },
                            ClassName = "TextButton",
                            Name = "EmptySlot",
                            Properties = {
                                AutoButtonColor = false,
                                BackgroundColor3 = Color3.new(0.835294187, 0.835294187, 0.835294187),
                                BackgroundTransparency = 0.5,
                                BorderColor3 = Color3.new(0, 0, 0),
                                BorderSizePixel = 0,
                                Font = Enum.Font.SourceSans,
                                Position = UDim2.new(0.1258993, 0, 0, 0),
                                Size = UDim2.new(0.118000001, 0, 1, 0),
                                Text = "",
                                TextColor3 = Color3.new(0, 0, 0),
                                TextSize = 14
                            }
                        },
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {}
                                }
                            },
                            ClassName = "TextButton",
                            Name = "EmptySlot",
                            Properties = {
                                AutoButtonColor = false,
                                BackgroundColor3 = Color3.new(0.835294187, 0.835294187, 0.835294187),
                                BackgroundTransparency = 0.5,
                                BorderColor3 = Color3.new(0, 0, 0),
                                BorderSizePixel = 0,
                                Font = Enum.Font.SourceSans,
                                Position = UDim2.new(0.1258993, 0, 0, 0),
                                Size = UDim2.new(0.118000001, 0, 1, 0),
                                Text = "",
                                TextColor3 = Color3.new(0, 0, 0),
                                TextSize = 14
                            }
                        },
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {}
                                }
                            },
                            ClassName = "TextButton",
                            Name = "EmptySlot",
                            Properties = {
                                AutoButtonColor = false,
                                BackgroundColor3 = Color3.new(0.835294187, 0.835294187, 0.835294187),
                                BackgroundTransparency = 0.5,
                                BorderColor3 = Color3.new(0, 0, 0),
                                BorderSizePixel = 0,
                                Font = Enum.Font.SourceSans,
                                Position = UDim2.new(0.1258993, 0, 0, 0),
                                Size = UDim2.new(0.118000001, 0, 1, 0),
                                Text = "",
                                TextColor3 = Color3.new(0, 0, 0),
                                TextSize = 14
                            }
                        },
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {}
                                }
                            },
                            ClassName = "TextButton",
                            Name = "EmptySlot",
                            Properties = {
                                AutoButtonColor = false,
                                BackgroundColor3 = Color3.new(0.835294187, 0.835294187, 0.835294187),
                                BackgroundTransparency = 0.5,
                                BorderColor3 = Color3.new(0, 0, 0),
                                BorderSizePixel = 0,
                                Font = Enum.Font.SourceSans,
                                Position = UDim2.new(0.1258993, 0, 0, 0),
                                Size = UDim2.new(0.118000001, 0, 1, 0),
                                Text = "",
                                TextColor3 = Color3.new(0, 0, 0),
                                TextSize = 14
                            }
                        }
                    },
                    ClassName = "ScrollingFrame",
                    Name = "ScrollingFrame",
                    Properties = {
                        BackgroundColor3 = Color3.new(1, 1, 1),
                        BackgroundTransparency = 1,
                        BorderColor3 = Color3.new(0, 0, 0),
                        BorderSizePixel = 0,
                        CanvasSize = UDim2.new(0, 0, 0, 0),
                        Position = UDim2.new(0.010999985, 0, 0.268000096, 0),
                        ScrollBarImageColor3 = Color3.new(0, 0, 0),
                        Size = UDim2.new(0.972999871, 0, 0.686999977, 0)
                    }
                }
            },
            ClassName = "Frame",
            Name = "He",
            Properties = {
                AnchorPoint = Vector2.new(0.5, 0.5),
                BackgroundColor3 = Color3.new(0, 0, 0),
                BackgroundTransparency = 0.699999988079071,
                BorderColor3 = Color3.new(0, 0, 0),
                BorderSizePixel = 0,
                Position = UDim2.new(0.499000013, 0, 0.619000018, 0),
                Size = UDim2.new(1, 0, 0.389999986, 0)
            }
        },
        {
            Attributes = {},
            Children = {},
            ClassName = "UISizeConstraint",
            Name = "UISizeConstraint",
            Properties = {
                MaxSize = Vector2.new(1200, 800)
            }
        }
    },
    ClassName = "Frame",
    Name = "ActiveTradeSession",
    Properties = {
        AnchorPoint = Vector2.new(0.5, 0.5),
        BackgroundColor3 = Color3.new(0.196078449, 0.196078449, 0.196078449),
        BorderColor3 = Color3.new(0, 0, 0),
        BorderSizePixel = 0,
        Position = UDim2.new(0.5, 0, 0.5, 0),
        Size = UDim2.new(0.608705521, 80, 0.627324998, 40),
        Visible = false,
        ZIndex = 2
    }
};