-- ClassName: ModuleScript
-- Roblox Path: game.ReplicatedStorage.Framework.GeneratedUI.GuiSpecParts.Gui_Shop_Abilities_11

-- Decompiled with Potassium's decompiler.

return {
    Attributes = {},
    Children = {
        {
            Attributes = {},
            Children = {},
            ClassName = "UICorner",
            Name = "UICorner",
            Properties = {}
        },
        {
            Attributes = {},
            Children = {
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UICorner",
                    Name = "UICorner",
                    Properties = {}
                },
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UIGridLayout",
                    Name = "UIGridLayout",
                    Properties = {
                        CellPadding = UDim2.new(0.00999999978, 0, 0.00999999978, 0),
                        CellSize = UDim2.new(0.189999998, 0, 0.449999988, 0),
                        SortOrder = Enum.SortOrder.LayoutOrder
                    }
                },
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UIPadding",
                    Name = "UIPadding",
                    Properties = {
                        PaddingLeft = UDim.new(0, 4),
                        PaddingTop = UDim.new(0, 4)
                    }
                }
            },
            ClassName = "ScrollingFrame",
            Name = "Buy",
            Properties = {
                AnchorPoint = Vector2.new(1, 0.5),
                AutomaticCanvasSize = Enum.AutomaticSize.Y,
                BackgroundColor3 = Color3.new(0, 0, 0),
                BackgroundTransparency = 0.5,
                BorderColor3 = Color3.new(0, 0, 0),
                BorderSizePixel = 0,
                Position = UDim2.new(1.00285208, 0, 0.563223243, 0),
                ScrollBarThickness = 8,
                Selectable = false,
                Size = UDim2.new(0.999324322, 0, 0.840980768, 0)
            }
        },
        {
            Attributes = {},
            Children = {
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UICorner",
                    Name = "UICorner",
                    Properties = {}
                },
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UIListLayout",
                    Name = "UIListLayout",
                    Properties = {
                        FillDirection = Enum.FillDirection.Horizontal,
                        Padding = UDim.new(0, 2),
                        SortOrder = Enum.SortOrder.LayoutOrder
                    }
                },
                {
                    Attributes = {},
                    Children = {
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UITextSizeConstraint",
                            Name = "UITextSizeConstraint",
                            Properties = {}
                        },
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {}
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UITextSizeConstraint",
                                    Name = "UITextSizeConstraint",
                                    Properties = {}
                                }
                            },
                            ClassName = "TextLabel",
                            Name = "Menu",
                            Properties = {
                                AnchorPoint = Vector2.new(0.5, 0.5),
                                BackgroundColor3 = Color3.new(0.443137288, 0.443137288, 0.443137288),
                                BackgroundTransparency = 1,
                                BorderColor3 = Color3.new(0, 0, 0),
                                BorderSizePixel = 0,
                                Font = Enum.Font.Unknown,
                                LayoutOrder = 1,
                                Position = UDim2.new(0.5, 0, 0.5, 0),
                                Size = UDim2.new(1.00000083, 0, 0.50440824, 0),
                                Text = "Buy",
                                TextColor3 = Color3.new(1, 1, 1),
                                TextScaled = true,
                                TextWrapped = true
                            }
                        }
                    },
                    ClassName = "TextButton",
                    Name = "Buy",
                    Properties = {
                        Active = false,
                        AnchorPoint = Vector2.new(0.5, 0.5),
                        AutoButtonColor = false,
                        BackgroundColor3 = Color3.new(0.325490206, 0.325490206, 0.325490206),
                        BackgroundTransparency = 0.20000000298023224,
                        BorderColor3 = Color3.new(0, 0, 0),
                        BorderSizePixel = 0,
                        LayoutOrder = 1,
                        Position = UDim2.new(0.0940517634, 0, 0.5, 0),
                        Selectable = false,
                        Size = UDim2.new(0.188103601, 0, 1, 0),
                        Text = ""
                    }
                },
                {
                    Attributes = {},
                    Children = {
                        {
                            Attributes = {},
                            Children = {},
                            ClassName = "UITextSizeConstraint",
                            Name = "UITextSizeConstraint",
                            Properties = {}
                        },
                        {
                            Attributes = {},
                            Children = {
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UICorner",
                                    Name = "UICorner",
                                    Properties = {}
                                },
                                {
                                    Attributes = {},
                                    Children = {},
                                    ClassName = "UITextSizeConstraint",
                                    Name = "UITextSizeConstraint",
                                    Properties = {}
                                }
                            },
                            ClassName = "TextLabel",
                            Name = "Menu",
                            Properties = {
                                AnchorPoint = Vector2.new(0.5, 0.5),
                                BackgroundColor3 = Color3.new(0.443137288, 0.443137288, 0.443137288),
                                BackgroundTransparency = 1,
                                BorderColor3 = Color3.new(0, 0, 0),
                                BorderSizePixel = 0,
                                Font = Enum.Font.Unknown,
                                LayoutOrder = 1,
                                Position = UDim2.new(0.5, 0, 0.5, 0),
                                Size = UDim2.new(1.00000083, 0, 0.50440824, 0),
                                Text = "Owned",
                                TextColor3 = Color3.new(1, 1, 1),
                                TextScaled = true,
                                TextWrapped = true
                            }
                        }
                    },
                    ClassName = "TextButton",
                    Name = "Owned",
                    Properties = {
                        Active = false,
                        AnchorPoint = Vector2.new(0.5, 0.5),
                        AutoButtonColor = false,
                        BackgroundColor3 = Color3.new(0.203921571, 0.203921571, 0.203921571),
                        BackgroundTransparency = 0.20000000298023224,
                        BorderColor3 = Color3.new(0, 0, 0),
                        BorderSizePixel = 0,
                        LayoutOrder = 2,
                        Position = UDim2.new(0.0940517634, 0, 0.5, 0),
                        Selectable = false,
                        Size = UDim2.new(0.188103601, 0, 1, 0),
                        Text = ""
                    }
                }
            },
            ClassName = "Frame",
            Name = "SelectSkins",
            Properties = {
                AnchorPoint = Vector2.new(1, 0.5),
                BackgroundColor3 = Color3.new(0, 0, 0),
                BackgroundTransparency = 0.6499999761581421,
                BorderColor3 = Color3.new(0, 0, 0),
                BorderSizePixel = 0,
                ClipsDescendants = true,
                Position = UDim2.new(0.989524305, 0, 0.0707493052, 0),
                Size = UDim2.new(0.972242475, 0, 0.117126115, 0)
            }
        },
        {
            Attributes = {},
            Children = {
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UICorner",
                    Name = "UICorner",
                    Properties = {}
                },
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UIGridLayout",
                    Name = "UIGridLayout",
                    Properties = {
                        CellPadding = UDim2.new(0.00999999978, 0, 0.00999999978, 0),
                        CellSize = UDim2.new(0.189999998, 0, 0.449999988, 0),
                        SortOrder = Enum.SortOrder.LayoutOrder
                    }
                },
                {
                    Attributes = {},
                    Children = {},
                    ClassName = "UIPadding",
                    Name = "UIPadding",
                    Properties = {
                        PaddingLeft = UDim.new(0, 4),
                        PaddingTop = UDim.new(0, 4)
                    }
                }
            },
            ClassName = "ScrollingFrame",
            Name = "Owned",
            Properties = {
                AnchorPoint = Vector2.new(1, 0.5),
                AutomaticCanvasSize = Enum.AutomaticSize.Y,
                BackgroundColor3 = Color3.new(0, 0, 0),
                BackgroundTransparency = 0.5,
                BorderColor3 = Color3.new(0, 0, 0),
                BorderSizePixel = 0,
                Position = UDim2.new(1.00285208, 0, 0.563223243, 0),
                ScrollBarThickness = 8,
                Selectable = false,
                Size = UDim2.new(0.999324322, 0, 0.840980768, 0),
                Visible = false
            }
        }
    },
    ClassName = "Frame",
    Name = "Abilities",
    Properties = {
        AnchorPoint = Vector2.new(1, 0.5),
        BackgroundColor3 = Color3.new(0, 0, 0),
        BackgroundTransparency = 0.5,
        BorderColor3 = Color3.new(0, 0, 0),
        BorderSizePixel = 0,
        ClipsDescendants = true,
        Position = UDim2.new(0.788063347, 0, 0.576163054, 0),
        Size = UDim2.new(0.773510516, 0, 0.815101027, 0),
        Visible = false
    }
};