-- ClassName: ModuleScript
-- Roblox Path: game.ReplicatedStorage.Framework.GeneratedUI.GuiSpecParts.Gui_Shop_title_5

-- Decompiled with Potassium's decompiler.

return {
    Attributes = {},
    Children = {
        {
            Attributes = {},
            Children = {},
            ClassName = "UICorner",
            Name = "UICorner",
            Properties = {}
        },
        {
            Attributes = {},
            Children = {},
            ClassName = "UITextSizeConstraint",
            Name = "UITextSizeConstraint",
            Properties = {}
        }
    },
    ClassName = "TextLabel",
    Name = "title",
    Properties = {
        AnchorPoint = Vector2.new(1, 0),
        BackgroundColor3 = Color3.new(0.172549024, 0.172549024, 0.172549024),
        BackgroundTransparency = 1,
        BorderColor3 = Color3.new(0, 0, 0),
        BorderSizePixel = 0,
        LayoutOrder = 2,
        Position = UDim2.new(0.965987742, 0, 0.313724726, 0),
        Size = UDim2.new(0.173899055, 0, 0.0475589111, 0),
        Text = "Gold",
        TextColor3 = Color3.new(1, 0.90196079, 0.431372553),
        TextScaled = true,
        TextWrapped = true,
        TextXAlignment = Enum.TextXAlignment.Right,
        FontFace = Font.new("rbxasset://fonts/families/Montserrat.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
        TextSize = 20,
        TextStrokeTransparency = 1,
        TextYAlignment = Enum.TextYAlignment.Center
    }
};